### ISSUE TITLE
C API feedback

### ISSUE THREAD

**Issue by bragadeesh** [ROCmSoftwarePlatform/rocFFT#1]
Lets use this issue tracker to comment on C API design.

**Comment by pavanky** [comment]
Is there any reason both input and output to the execute function are pointers to arrays?https://github.com/RadeonOpenCompute/rocFFT/blob/master/src/include/rocfft.h#L91

Shouldn't the input just be an array and output be pointer to an array ideally ?

**Comment by pavanky** [comment]
Now that I think about it, neither one of them needs to be a pointer to an array since output is pre-allocated.

Is this done in case the n transforms are not part of the same buffer?

**Comment by bragadeesh** [comment]
@pavanky  the reason is to support planar formats. Both in & out are pointers to array of void-pointers. This 'array' length is either 1 or 2. It is 1 if the data is in complex interleaved format (1 buffer has both real & imaginary) and 2 if the data is in complex planar format (real and imaginary in separate buffers).

**Comment by pavanky** [comment]
@bragadeesh Yeah that makes sense. thanks for the clarification.
