### ISSUE TITLE
install.sh fails on ROCm 1.7

### ISSUE THREAD

**Issue by rwvo** [ROCmSoftwarePlatform/rocFFT#112]
issuing "./install.sh -i -d -c" fails with a compilation error

### What is the expected behavior
I would expect the script to run to completion without errors.  

### What actually happens
Here's to script output:

[ 54%] Building CXX object clients/samples/fixed-large/CMakeFiles/fixed-large-double.dir/fixed-large-double.cpp.o
Scanning dependencies of target fixed-16-float
Scanning dependencies of target rocfft-rider
[ 56%] Building CXX object clients/samples/fixed-large/CMakeFiles/fixed-large-float.dir/fixed-large-float.cpp.o
[ 59%] Building CXX object clients/samples/fixed-16/CMakeFiles/fixed-16-double.dir/fixed-16-double.cpp.o
[ 61%] Building CXX object clients/rider/CMakeFiles/rocfft-rider.dir/rider.cpp.o
[ 65%] Building CXX object clients/rider/CMakeFiles/rocfft-rider.dir/misc.cpp.o
[ 65%] Building CXX object clients/samples/fixed-16/CMakeFiles/fixed-16-float.dir/fixed-16-float.cpp.o
Scanning dependencies of target rocfft-selftest
[ 68%] Building CXX object clients/selftest/CMakeFiles/rocfft-selftest.dir/test_complex.cpp.o
Scanning dependencies of target rocfft-test
[ 70%] Building CXX object clients/tests/CMakeFiles/rocfft-test.dir/gtest_main.cpp.o
In file included from /home/rvanoo/repos/rocFFT/clients/samples/fixed-large/fixed-large-double.cpp:12:
/opt/rocm/hip/include/hip/hip_runtime_api.h:276:2: error: ("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
#error("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");

Looking at the script, it seems that hcc is used to compile HIP sources, without defining __HIP_PLATFORM_HCC__ (which is what hipcc would otherwise take care of). I tried setting the missing #define as an environment variable, but that didn't seem to get passed on to hcc.

### How to reproduce
by issuing "./install.sh -i -d -c"

### Environment
Intel Core i7 6700K, AMD Radeon R9 Nano (fiji), ROCm 1.7 stack installed from the AMD ROCm repositories (repo.radeon.com)

rocm-dkms/Ubuntu 16.04,now 1.7.60 amd64 [installed]

Linux snell 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bragadeesh** [comment]
What branch are you building? Did this succeed before or are you building for the first time with rocm 1.7.0?
We have had some build fails today, but it looks your error message is something else

**Comment by rwvo** [comment]
This is on the develop branch of rocFFT, which seems to be the default branch. This is a first-time build for me. I initially followed the build instructions on the wiki under "Build Library + Tests + Benchmarks + Samples Using Individual Commands". That succeeded, but then when I wanted to run the benchmarks, as per the wiki instructions under "Clients", rocfft-rider was not available in the build directory. That's why I next tried building using install.sh, with the -c option, hoping that this would give me the client binaries too.

**Comment by kknox** [comment]
Try it today; you may have just cloned the repo just as we made a checkin that broke the build.  I think i fixed it in #113, so give it another shot. Its passing now in our CI.  Use the `install -cd` command and let me know how it goes.

**Comment by rwvo** [comment]
I'm getting the same error during the building of the clients when doing `install -cd`:
/opt/rocm/hip/include/hip/hip_runtime_api.h:276:2: error: ("Must define exactly one of `__HIP_PLATFORM_HCC__` or `__HIP_PLATFORM_NVCC__`");
#error("Must define exactly one of `__HIP_PLATFORM_HCC__` or `__HIP_PLATFORM_NVCC__`");

This is on the development branch, commit 0f8cd3, pulled today:
```
commit 0f8cd3384cd0a566c4a0821f9a0b4103097dc2a3
Merge: 7e94e50 2eab715
Author: Bragadeesh Natarajan <bragadeesh@users.noreply.github.com>
Date:   Tue Jan 30 14:36:37 2018 -0800

    Merge pull request #113 from kknox/build-fix
    
    Fixing include paths for cmake targets
```

**Comment by bragadeesh** [comment]
If you run: /opt/rocm/bin/hipconfig
what does it show?

**Comment by rwvo** [comment]
I'll answer that below. I'm on to something: when I run the install.sh script, build/release/compile_commands.json has a lot of matches for `__HIP_PLATFORM_NVCC__`, while I am on an AMD system (the only gpu is a Fiji). For instance:
```
{
  "directory": "/home/rvanoo/repos/rocFFT/build/release/clients/samples/fixed-16",
  "command": "/opt/rocm/bin/hcc  -D__HIP_PLATFORM_NVCC__ -I/home/rvanoo/repos/rocFFT/clients/samples/fixed-16/../include -I/opt/rocm/hip/include -I/home/rvanoo/repos/rocFFT/library/include/rocfft -I/home/rvanoo/repos/rocFFT/build/release/include/rocfft -I/home/rvanoo/repos/rocFFT/library/include -I/home/rvanoo/repos/rocFFT/build/release/include  -O3 -DNDEBUG   -Wno-unused-command-line-argument -std=c++11 -o CMakeFiles/fixed-16-float.dir/fixed-16-float.cpp.o -c /home/rvanoo/repos/rocFFT/clients/samples/fixed-16/fixed-16-float.cpp",
  "file": "/home/rvanoo/repos/rocFFT/clients/samples/fixed-16/fixed-16-float.cpp"
},
```
When I manually build rocFFT (i.e., `mkdir -p build/release`, `cd build/release`, `cmake ../..`), these do not appear in compile_commands.json.

While this system has only an AMD GPU, it does have a CUDA installation too (needed for unrelated HIP work). Perhaps this tricks the install.sh script into thinking it runs on an NVIDIA system. This was an issue with older versions of hipcc too.

/opt/rocm/bin/hipconfig gives me this:
```
HIP version  : 1.4.17494

== hipconfig
HIP_PATH     : /opt/rocm
HIP_PLATFORM : hcc
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/opt/rocm/include -I/opt/rocm/hcc/include

== hcc
HSA_PATH     : /opt/rocm/hsa
HCC_HOME     : /opt/rocm/hcc
HCC clang version 6.0.0 (ssh://gerritgit/compute/ec/hcc-tot/clang 42ceed861a212d9bd0aef883ee7981144f3ecc02) (ssh://gerritgit/compute/ec/hcc-tot/llvm 23e086be6f627e6e983c6789d2e77da6bf85ebb6) (based on HCC 1.1.17493-2f85d8a-42ceed8-23e086b )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
Can't exec "/opt/rocm/hcc/compiler/bin/llc": No such file or directory at /opt/rocm/bin/hipconfig line 132.
HCC-cxxflags :  -hc -std=c++amp -I/opt/rocm/hcc-1.0/include -I/opt/rocm/includeHCC-ldflags  :  -hc -std=c++amp -L/opt/rocm/hcc-1.0/lib -Wl,--rpath=/opt/rocm/hcc-1.0/lib -ldl -lm -lpthread -lunwind -lhc_am -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive

=== Environment Variables
PATH=/home/rvanoo/bin:/home/rvanoo/.local/bin:/home/rvanoo/bin:/home/rvanoo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/rocm/bin:/opt/rocm/bin
HIP_PLATFORM=hcc

== Linux Kernel
Hostname     : snell
Linux snell 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

**Comment by bragadeesh** [comment]
ok, looks like that cuda presence is the problem, it confuses the build system to use hipcc instead of hcc

**Comment by bragadeesh** [comment]
@kknox how do we prevent this?
also it might help to get -v switch to the install script to enable VERBOSE output and we can ask user to post build log when they have build problem

**Comment by rwvo** [comment]
In the meanwhile, I managed to build/install rocFFT manually, as I described above, and I also built rocfft-rider. But when I run the example from the wiki, I get an error:
```
[rvanoo@snell:~/repos/rocFFT/build/release/clients/staging] $ ./rocfft-rider -x 1024 -b 1000 -p 100
HIP_V_THROWERROR< 1030 > (/home/rvanoo/repos/rocFFT/clients/rider/misc.cpp Line: 20): hipMalloc failed
rocfft error condition reported:
HIP_V_THROWERROR< 1030 > (/home/rvanoo/repos/rocFFT/clients/rider/misc.cpp Line: 20): hipMalloc failed
```

I have other HIP codes on this machine that also use hipMalloc (of course), and these work just fine. Any idea? I'll make a debug build, and see if I can find out what is going on.

**Comment by bragadeesh** [comment]
are there other GPU apps running? Fiji should have enough device memory to run those cases, not sure why it cannot find memory.

**Comment by kknox** [comment]
Yes, I think you are correct.  The cmake code uses the presence of CUDA to determine if it should compile for a [CUDA backend](https://github.com/ROCmSoftwarePlatform/rocFFT/search?utf8=%E2%9C%93&q=CUDA_FOUND&type=)

I think i need to add a new configure flag to allow a user to pick the backend they want, instead of making assumptions.  If you can, try to uninstall the CUDA SDK.  Also, If you are familiar with docker, you could build rocfft in a clean rocm docker container.

**Comment by rwvo** [comment]
I just commented out the `if( CUDA_FOUND )` branch in the CMakeLists.txt for rocfft-rider, and this got me a working version. The docker solution would be cleaner, pending the new config flag, but I'm not super-familiar with that, so I'll go with the dirty workaround for now.

Thanks for the quick help to both of you.

**Comment by kknox** [comment]
OK, that's clever and I'm glad you are up and going.  In the future, if you need to rebuild, you could probably just [comment out this line](https://github.com/ROCmSoftwarePlatform/rocFFT/blob/develop/CMakeLists.txt#L127), and that would force CUDA_FOUND to be uninitialized and therefore evaluate to false.
