### ISSUE TITLE
Comparison with clFFT (performance)

### ISSUE THREAD

**Issue by preda** [ROCmSoftwarePlatform/rocFFT#114]
This is a documentation request:

could you please publish a performance comparison with clFFT.

**Comment by preda** [comment]
I did a few preliminary comparison myself, using double, complex transform, FFT sizes 2^9, 2^18, 2^21, and in all cases clFFT was much faster.

I think improving performance, to achieve at least parity with clFFT is paramount. And afterwards, parity with cuFFT.

**Comment by bragadeesh** [comment]
Thanks for your comment, yes we are working to get there!

**Comment by preda** [comment]
Three years later, did rocFFT reach performance parity with clFFT?

**Comment by feizheng10** [comment]
Yes, for some of the cases! And faster for some of non-power-of-2 cases.
