### ISSUE TITLE
Build failure on Ubuntu 17.10

### ISSUE THREAD

**Issue by preda** [ROCmSoftwarePlatform/rocFFT#115]
From fresh source checkout, the build fails with objdump: /usr/lib/x86_64-linux-gnu/libm.a: File format not recognised

Although in the end, these files are generated, so maybe it's not a hard error but just a misleading message..?

~/rocFFT/build$ find . -name "*so*"
./release/library/src/librocfft.so
./release/library/src/device/librocfft-device.so.0.8.1.0
./release/library/src/device/librocfft-device.so
./release/library/src/device/librocfft-device.so.0
./release/library/src/librocfft.so.0
./release/library/src/librocfft.so.0.8.1.0
./release/compile_commands.json

~/rocFFT$ ./install.sh -d
Creating project build directory in: ./build
Hit:1 http://archive.ubuntu.com/ubuntu artful InRelease                                      
Hit:2 http://archive.canonical.com/ubuntu artful InRelease                                    
Hit:3 http://repo.radeon.com/rocm/apt/debian xenial InRelease                                 
Get:4 http://archive.ubuntu.com/ubuntu artful-updates InRelease [78.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu artful-backports InRelease [72.2 kB]
Get:6 http://archive.ubuntu.com/ubuntu artful-security InRelease [78.6 kB]
Get:7 http://archive.ubuntu.com/ubuntu artful-updates/main Sources [78.8 kB]
Get:8 http://archive.ubuntu.com/ubuntu artful-updates/universe Sources [22.8 kB]
Get:9 http://archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages [191 kB]
Get:10 http://archive.ubuntu.com/ubuntu artful-updates/main i386 Packages [188 kB]
Get:11 http://archive.ubuntu.com/ubuntu artful-updates/main Translation-en [87.6 kB]
Get:12 http://archive.ubuntu.com/ubuntu artful-updates/main amd64 DEP-11 Metadata [73.3 kB]
Get:13 http://archive.ubuntu.com/ubuntu artful-updates/main DEP-11 64x64 Icons [44.9 kB]
Get:14 http://archive.ubuntu.com/ubuntu artful-updates/universe i386 Packages [76.7 kB]
Get:15 http://archive.ubuntu.com/ubuntu artful-updates/universe amd64 Packages [77.2 kB]
Get:16 http://archive.ubuntu.com/ubuntu artful-updates/universe Translation-en [44.4 kB]
Get:17 http://archive.ubuntu.com/ubuntu artful-updates/universe amd64 DEP-11 Metadata [49.5 kB]
Get:18 http://archive.ubuntu.com/ubuntu artful-updates/universe DEP-11 64x64 Icons [55.3 kB]
Get:19 http://archive.ubuntu.com/ubuntu artful-backports/universe amd64 DEP-11 Metadata [4,700 B]
Get:20 http://archive.ubuntu.com/ubuntu artful-security/main Sources [34.6 kB]
Get:21 http://archive.ubuntu.com/ubuntu artful-security/universe Sources [10.2 kB]
Get:22 http://archive.ubuntu.com/ubuntu artful-security/main i386 Packages [88.8 kB]
Get:23 http://archive.ubuntu.com/ubuntu artful-security/main amd64 Packages [90.5 kB]
Get:24 http://archive.ubuntu.com/ubuntu artful-security/main Translation-en [43.6 kB]
Get:25 http://archive.ubuntu.com/ubuntu artful-security/main amd64 DEP-11 Metadata [2,924 B]
Get:26 http://archive.ubuntu.com/ubuntu artful-security/universe i386 Packages [34.7 kB]
Get:27 http://archive.ubuntu.com/ubuntu artful-security/universe amd64 Packages [34.8 kB]
Get:28 http://archive.ubuntu.com/ubuntu artful-security/universe Translation-en [22.2 kB]
Get:29 http://archive.ubuntu.com/ubuntu artful-security/universe amd64 DEP-11 Metadata [10.4 kB]
Get:30 http://archive.ubuntu.com/ubuntu artful-security/universe DEP-11 64x64 Icons [10.2 kB]
Fetched 1,607 kB in 5s (305 kB/s)                                        
Reading package lists... Done
Building dependency tree       
Reading state information... Done
12 packages can be upgraded. Run 'apt list --upgradable' to see them.
~/rocFFT ~/rocFFT
-- The CXX compiler identification is Clang 6.0.0
-- Check for working CXX compiler: /opt/rocm/bin/hcc
-- Check for working CXX compiler: /opt/rocm/bin/hcc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HCC compiler set; ROCm backend selected [ CXX=/opt/rocm/bin/hcc cmake ... ]
-- Building with ROCm tools
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libunwind'
--   Found libunwind, version 1.1
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/preda/rocFFT/build/release
Scanning dependencies of target rocfft-kernel-generator
[  8%] Building CXX object library/src/device/generator/CMakeFiles/rocfft-kernel-generator.dir/generator.file.cpp.o
[  8%] Building CXX object library/src/device/generator/CMakeFiles/rocfft-kernel-generator.dir/generator.main.cpp.o
[ 13%] Linking CXX executable rocfft-kernel-generator
[ 13%] Built target rocfft-kernel-generator
[ 17%] Generator producing device kernels for rocfft-device
Scanning dependencies of target rocfft-device
[ 21%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/transpose.cpp.o
[ 26%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/complex2real.cpp.o
[ 30%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/kernel_launch_double.cpp.o
[ 39%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/real2complex.cpp.o
[ 43%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/kernel_launch_double_large.cpp.o
[ 34%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/function_pool.cpp.o
[ 47%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/kernel_launch_single_large.cpp.o
[ 52%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/kernel_launch_single.cpp.o
[ 56%] Linking CXX shared library librocfft-device.so
objdump: /usr/lib/x86_64-linux-gnu/libm.a: File format not recognised
[ 56%] Built target rocfft-device
Scanning dependencies of target rocfft
[ 60%] Building CXX object library/src/CMakeFiles/rocfft.dir/hipfft.cpp.o
[ 73%] Building CXX object library/src/CMakeFiles/rocfft.dir/get_radix.cpp.o
[ 73%] Building CXX object library/src/CMakeFiles/rocfft.dir/repo.cpp.o
[ 78%] Building CXX object library/src/CMakeFiles/rocfft.dir/twiddles.cpp.o
[ 65%] Building CXX object library/src/CMakeFiles/rocfft.dir/transform.cpp.o
[ 82%] Building CXX object library/src/CMakeFiles/rocfft.dir/powX.cpp.o
[ 95%] Building CXX object library/src/CMakeFiles/rocfft.dir/kargs.cpp.o
[ 86%] Building CXX object library/src/CMakeFiles/rocfft.dir/plan.cpp.o
[ 91%] Building CXX object library/src/CMakeFiles/rocfft.dir/auxiliary.cpp.o
[100%] Linking CXX shared library librocfft.so
objdump: /usr/lib/x86_64-linux-gnu/libm.a: File format not recognised
[100%] Built target rocfft

**Comment by preda** [comment]
Another problem, on "install.sh -c" I get build failure because of GTEST_LIBRARY.

I did "apt install libgtest-dev", but that didn't fix it.
How am I supposed to fix the build (get GTEST_LIBRARY)?
(on Ubuntu 17.10).

~/rocFFT$ ./install.sh -c
Creating project build directory in: ./build
~/rocFFT ~/rocFFT
-- The CXX compiler identification is Clang 6.0.0
-- Check for working CXX compiler: /opt/rocm/bin/hcc
-- Check for working CXX compiler: /opt/rocm/bin/hcc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HCC compiler set; ROCm backend selected [ CXX=/opt/rocm/bin/hcc cmake ... ]
-- Building with ROCm tools
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libunwind'
--   Found libunwind, version 1.1
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found FFTW: /usr/include (Required is at least version "3.0") 
-- FindFFTW configured variables:
-- FFTW_INCLUDE_DIRS: /usr/include
-- FFTW_LIBRARIES: /usr/lib/x86_64-linux-gnu/libfftw3f.so;/usr/lib/x86_64-linux-gnu/libfftw3.so
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   program_options
CMake Error at /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.9/Modules/FindGTest.cmake:146 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  clients/tests/CMakeLists.txt:42 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/preda/rocFFT/build/release/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.

**Comment by preda** [comment]
And the third build-related issue is:
To me it's not very clear how to use the "install.sh" script. I don't want to do a "global install", thus I stayed away from "install.sh -i".

I did first "install -d", in the idea that this would get the dependencies. This too a very long time, and finally did build the .so library. But it did not build the client.

So next I did "install -c" to build the client. SURPRISE, this started by deleting the library (.so) that it took so long to build previously... not good. Afterwards, it stopped because of the GTEST problem above.

**Comment by kknox** [comment]
@scchan @whchung 
Have you seen those libm.a errors before?

@preda 
I have never tested on Ubuntu 17.10, so I can only imagine that the compiler that ships in 17.10 is newer, there is probably an incompatibility with that shipping libm.a and hcc.  My 2c.  Try building on Ubuntu 16.04; use a docker container to make it easy on yourself.

As for the install.sh script, it's there to try to make building easier, but it's not as flexible as cmake itself, and neither should it be.  

When invoking the install script, try using `./install -cd`.  You are telling that script that you want to build the clients, and you want to build/download dependencies at the same time.  Gtest is a dependency of our test clients.  If you specify only -c, it won't download dependencies at all, and if you specify only -d it will only download the dependencies of the library proper and not the clients.  `-cd` is required to build googletest.  

Yes, `-i` installs globally, and there there is no way yet to specify an alternative directory.  You can build with cmake directly if you want to provide your own CMAKE_INSTALL_PREFIX.

**Comment by kknox** [comment]
Forgot to mention that the rocfft wiki has the [manual build instructions](https://github.com/ROCmSoftwarePlatform/rocFFT/wiki/Build) for expert users:

**Comment by preda** [comment]
@kknox :  thank you for the explanation. I did build successfully (on Ubuntu 17.10) using "install.sh -cd" including the rocfft-rider client.

The error about "libm.a" seems innocuous; everything was OK.

It may be useful to add the make-based build instructions to README.md

Feel free to close this issue now.

**Comment by mvermeulen** [comment]
@bragadeesh @kknox 
For what it is worth, I see the same "libm.a" error on Ubuntu 18.04 even linking a simple saxpy example:

My diagnosis is as follows:
1. strace shows that "clamp-link" calls "objdump -t" on the libm.a file to grep for .kernel symbols.
2. objdump expects the /usr/lib/x86_64-linux-gnu/libm.a file to be an archive file.
3. On my Ubuntu 18.04 system at least, the file has become GNU ld script with contents:
/* GNU ld script
*/
OUTPUT_FORMAT(elf64-x86-64)
GROUP ( /usr/lib/x86_64-linux-gnu/libm-2.27.a /usr/lib/x86_64-linux-gnu/libmvec.a )

Since objdump doesn't know about this new file type (it assumes an ASCII file), the warning is emitted. If the libm.a and libvec.a don't have .kernel symbols being searched, I'd expect this to be innocuous.

So I think this is a more general ROCm build error that can happen with a mismatch at the link step between libm.a and the clamp-link steps.
