### ISSUE TITLE
Unable to locate package rocfft

### ISSUE THREAD

**Issue by max0x7ba** [ROCmSoftwarePlatform/rocFFT#119]
### What is the expected behavior
rocfft is installed.  

### What actually happens
E: Unable to locate package rocfft

### How to reproduce
```
max@supernova:~$ cat /etc/apt/sources.list.d/rocm.list
deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main
max@supernova:~$ sudo apt install rocfft
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package rocfft
```
On the other hand, I was able to install `rocm-dkms` and `rocm-opencl-dev` from rocm repo successfully:

```
max@supernova:~$ sudo apt-get install rocm-dkms rocm-opencl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
rocm-dkms is already the newest version (1.7.60).
rocm-opencl-dev is already the newest version (1.2.0-2017121952).
```

### Environment
```
max@supernova:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

**Comment by bragadeesh** [comment]
rocfft was not included in the last release of rocm; it will be available in the next release

**Comment by max0x7ba** [comment]
Why was it not included int the last release of rocm please?

**Comment by tingxingdong** [comment]
You can build rocFFT from source always. Current ROCM release is 1.7.0, next release 1.7.1 will include rocFFT very soon.  You won't wait long

**Comment by bragadeesh** [comment]
actually rocm 1.7.137 has been released, and rocfft is included in that

**Comment by bragadeesh** [comment]
update your rocm-dkms to the most recent version and you should be able to install rocfft also
