### ISSUE TITLE
Need hipfft interfaces to properly use hipcomplex types in HIP

### ISSUE THREAD

**Issue by whchung** [ROCmSoftwarePlatform/rocFFT#121]
### What is the expected behavior
-  hipComplex types be used to implement hipfft interfaces

### What actually happens
-  https://github.com/ROCmSoftwarePlatform/rocFFT/blob/develop/library/include/rocfft/hipfft.h#L49

Incorrectly defined `float[2]` or `double[2]` without properly using data types defined in HIP.

Relevant commit in TensorFlow ROCm port:
https://github.com/ROCmSoftwarePlatform/tensorflow/commit/ed6bf17441a1cfd808cac127fff6da830f4e8ec8

**Comment by bragadeesh** [comment]
I have merged tensorflow branch into develop, next official packages of rocFFT should include this issue, should this remain open, or can you close?

**Comment by whchung** [comment]
Thanks let me update TensorFlow port and make sure it builds and runs then close the ticket

**Comment by whchung** [comment]
@bragadeesh TensorFlow builds with `develop` branch fine now. As most of users of TensorFlow would use `rocfft` in binary form as one of the components in ROCm stack, let me leave the ticket open for now and close it when the next ROCm release is published.

**Comment by malcolmroberts** [comment]
@bragadeesh , is this issue resolved?

**Comment by bragadeesh** [comment]
I am closing this old issue; @whchung can reopen if this still a concern
