### ISSUE TITLE
Not able to build from source on nvidia Platform

### ISSUE THREAD

**Issue by mn265** [ROCmSoftwarePlatform/rocFFT#125]
### What is the expected behavior
-  I am trying to build rocFFT from source on NVIDIA platform.

### What actually happens
-  but during make it will got hang (after completing 52%)

### How to reproduce
-  

### Environment
-nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0 Off |                  N/A |
| 47%   33C    P8    N/A /  75W |      0MiB /  4040MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro M2000        Off  | 00000000:02:00.0 Off |                  N/A |
| 56%   33C    P8     7W /  75W |      0MiB /  4043MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

-- ./hipconfig
HIP version  : 1.5.18151

== hipconfig
HIP_PATH     : /opt/rocm/hip
HIP_PLATFORM : nvcc
CPP_CONFIG   :  -D__HIP_PLATFORM_NVCC__=  -I/opt/rocm/hip/include -I/usr/local/cuda/include

== nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Wed_Apr_11_23:16:29_CDT_2018
Cuda compilation tools, release 9.2, V9.2.88

=== Environment Variables
PATH=/home/usr/bin:/home/usr/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin:/opt/rocm/hip/bin:/opt/rocm/bin
HIP_PATH=/opt/rocm/hip
CUDA_PATH=/usr/local/cuda

== Linux Kernel
Hostname     : usr
Linux usr 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

###error log:
[  4%] Building CXX object library/src/device/generator/CMakeFiles/rocfft-kernel-generator.dir/generator.file.cpp.o
[  8%] Building CXX object library/src/device/generator/CMakeFiles/rocfft-kernel-generator.dir/generator.main.cpp.o
/home/usr

/rocFFT/library/src/device/generator/generator.file.cpp(43): warning: variable "real_transform" was declared but never referenced
/rocFFT/library/src/device/generator/generator.file.cpp(51): warning: variable "batchsize" was declared but never referenced
/rocFFT/library/src/device/generator/generator.file.cpp(84): warning: variable "realSpecial_Nr" was declared but never referenced
/rocFFT/library/src/device/generator/generator.kernel.hpp(219): warning: variable "iStride" was declared but never referenced
          detected during instantiation of "StockhamGenerator::Kernel<PR>::Kernel(const FFTKernelGenKeyParams &) [with PR=(rocfft_precision)0]" 
/rocFFT/library/src/device/generator/generator.file.cpp(466): here
/rocFFT/library/src/device/generator/generator.kernel.hpp(219): warning: variable "oStride" was declared but never referenced
          detected during instantiation of "StockhamGenerator::Kernel<PR>::Kernel(const FFTKernelGenKeyParams &) [with PR=(rocfft_precision)0]" 
/rocFFT/library/src/device/generator/generator.file.cpp(466): here
/rocFFT/library/src/device/generator/generator.kernel.hpp(707): warning: integer conversion resulted in a change of sign
/rocFFT/library/src/device/generator/generator.kernel.hpp(709): warning: integer conversion resulted in a change of sign
/home/usr/rocFFT/library/src/device/generator/generator.kernel.hpp(660): warning: variable "cReg" was declared but never referenced
/rocFFT/library/src/device/generator/generator.kernel.hpp(707): warning: integer conversion resulted in a change of sign
/rocFFT/library/src/device/generator/generator.kernel.hpp(709): warning: integer conversion resulted in a change of sign
/rocFFT/library/src/device/generator/generator.kernel.hpp(707): warning: integer conversion resulted in a change of sign
/rocFFT/library/src/device/generator/generator.kernel.hpp(709): warning: integer conversion resulted in a change of sign

[ 13%] Linking CXX executable rocfft-kernel-generator
[ 13%] Built target rocfft-kernel-generator
[ 17%] Generator producing device kernels for rocfft-device
Scanning dependencies of target rocfft-device
[ 21%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/function_pool.cpp.o
[ 26%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/transpose.cpp.o
[ 30%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/complex2real.cpp.o
[ 34%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/real2complex.cpp.o
[ 39%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/kernel_launch_double.cpp.o
[ 43%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/kernel_launch_single.cpp.o
[ 47%] Building CXX object library/src/device/CMakeFiles/rocfft-device.dir/kernel_launch_single_large.cpp.o
/opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h: In function ‘hipError_t hipCtxDetach(hipCtx_t)’:
/opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h:1019:30: warning: ‘CUresult cuCtxDetach(CUcontext)’ is deprecated [-Wdeprecated-declarations]
     return hipCUResultTohipError(cuCtxDetach(ctx));
                              ^
                                    ^
/opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h: In function ‘hipError_t hipDeviceComputeCapability(int*, int*, hipDevice_t)’:
/opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h:1027:30: warning: ‘CUresult cuDeviceComputeCapability(int*, int*, CUdevice)’ is deprecated [-Wdeprecated-declarations]
     return hipCUResultTohipError(cuDeviceComputeCapability(major, minor, device));
                              ^
/usr/local/cuda/include/cuda.h:2528:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuDeviceComputeCapability(int *major, int *minor, CUdevice dev);
                                    ^
/opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h:1027:30: warning: ‘CUresult cuDeviceComputeCapability(int*, int*, CUdevice)’ is deprecated [-Wdeprecated-declarations]
     return hipCUResultTohipError(cuDeviceComputeCapability(major, minor, device));
                              ^
/usr/local/cuda/include/cuda.h:2528:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuDeviceComputeCapability(int *major, int *minor, CUdevice dev);
                                    ^
/opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h:1027:76: warning: ‘CUresult cuDeviceComputeCapability(int*, int*, CUdevice)’ is deprecated [-Wdeprecated-declarations]
     return hipCUResultTohipError(cuDeviceComputeCapability(major, minor, device));
                                                                            ^
/usr/local/cuda/include/cuda.h:2528:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuDeviceComputeCapability(int *major, int *minor, CUdevice dev);

it will hang from here....

**Comment by feizheng10** [comment]
Check the commit 828de1a, and ping issue 276

**Comment by malcolmroberts** [comment]
It should be possible to compile for the NVIDIA by using clang's cuda compiler.  This isn't an officially supported compilation path, so we can't guarantee that it will work in all situations.
