### ISSUE TITLE
How to port FFT library(cuFFT) for HIP port to work on cuda and  ROCm platforms

### ISSUE THREAD

**Issue by sriharikarnam** [ROCmSoftwarePlatform/rocFFT#134]
In the context of HIP port of ML Frameworks,how to port FFT library(cuFFT) for HIP port to work on cuda and ROCm platforms.

 For other libraries like cublas,it is found hipBLAS is a marshaling library, it marshals inputs and outputs from either cuBLAS or rocBLAS for each respective platform.

Is there any marshalling library for FFT or  rocFFT will work for cuda and rocm platforms

**Comment by ex-rzr** [comment]
There is hipFFT:
https://github.com/ROCmSoftwarePlatform/rocFFT/blob/develop/library/include/hipfft.h

**Comment by sriharikarnam** [comment]
@ex-rzr 
We have depicted the problem statement in the attachment. Please suggest accordingly
[cuFFT_rocFFT HIP Port.pdf](https://github.com/ROCmSoftwarePlatform/rocFFT/files/2395796/cuFFT_rocFFT.HIP.Port.pdf)

**Comment by feizheng10** [comment]
We don't have a marshalling library(like hipBlas) to cover both cuFFT and rocFFT yet.
For porting cuda code to ROCm/HIP, the typical way is:
* hipfy CUDA runtime API functions
* manually change any cu* libraries APIs to its hip version
* link aginst to ROCm runtime and other library

**Comment by malcolmroberts** [comment]
hipFFT, available in a separate repo, (https://github.com/ROCmSoftwarePlatform/hipFFT) should work for this issue.
