### ISSUE TITLE
Status of hipFFT

### ISSUE THREAD

**Issue by ex-rzr** [ROCmSoftwarePlatform/rocFFT#135]
What features of cuFFT are actually implemented?
It's hard to say looking at header and source files.

1. There is a lot of commented code and empty switch cases, for example: https://github.com/ROCmSoftwarePlatform/rocFFT/blob/develop/library/src/hipfft.cpp#L224

2. `hipfftExecC2C` calls the same code for different directions (unlike `hipfftExecZ2Z`):
https://github.com/ROCmSoftwarePlatform/rocFFT/blob/develop/library/src/hipfft.cpp#L858

3. Functions always return `HIPFFT_SUCCESS` and ignore result of `rocfft_*` functions.

4. Will hipFFT be a wrapper around cuFFT? Or it's supposed to be used with rocFFT only (on both ROCm and CUDA).

**Comment by bragadeesh** [comment]
hipFFT is a wrapper on top of rocFFT that was written to provide compatible interfaces. As you can see it is not fully done yet and is missing functionalities and has bugs; goal is to clean this out and get it tested well, unfortunately I don't have timeline on when that will happen
