### ISSUE TITLE
The wrong result using hipfft samples

### ISSUE THREAD

**Issue by holyprince** [ROCmSoftwarePlatform/rocFFT#193]
When I use hipfft on my program, I find the result always is 0.

So I try the sample from this :clients/samples/hipfft/hipfft_planmany_2d_z2z.cpp
[https://github.com/ROCmSoftwarePlatform/rocFFT/blob/develop/clients/samples/hipfft/hipfft_planmany_2d_z2z.cpp](url)
and the following is the result:
the hipfft output is different with fftw output.
### What actually happens
-  
fftw inputs:
[+0, +0] : ( +7.00,  +7.00)  [+0, +1] : ( +8.00,  +8.00)  [+0, +2] : ( +9.00,  +9.00)  [+0, +3] : (+10.00, +10.00)  [+0, +4] : (+11.00, +11.00)  [+0, +5] : ( +0.00,  +0.00)
[+1, +0] : ( +1.00,  +1.00)  [+1, +1] : ( +2.00,  +2.00)  [+1, +2] : ( +3.00,  +3.00)  [+1, +3] : ( +4.00,  +4.00)  [+1, +4] : ( +5.00,  +5.00)  [+1, +5] : ( +6.00,  +6.00)
[+2, +0] : ( +7.00,  +7.00)  [+2, +1] : ( +8.00,  +8.00)  [+2, +2] : ( +9.00,  +9.00)  [+2, +3] : (+10.00, +10.00)  [+2, +4] : (+11.00, +11.00)  [+2, +5] : ( +0.00,  +0.00)
[+3, +0] : ( +1.00,  +1.00)  [+3, +1] : ( +2.00,  +2.00)  [+3, +2] : ( +3.00,  +3.00)  [+3, +3] : ( +4.00,  +4.00)  [+3, +4] : ( +5.00,  +5.00)  [+3, +5] : ( +6.00,  +6.00)
[+4, +0] : ( +7.00,  +7.00)  [+4, +1] : ( +8.00,  +8.00)  [+4, +2] : ( +9.00,  +9.00)  [+4, +3] : (+10.00, +10.00)  [+4, +4] : (+11.00, +11.00)  [+4, +5] : ( +0.00,  +0.00)
fftw outputs:
[+0, +0] : (+177.00, +177.00)  [+0, +1] : (-27.80, -38.20)  [+0, +2] : (+25.52, -19.52)  [+0, +3] : (+21.00, +21.00)  [+0, +4] : (-19.52, +25.52)  [+0, +5] : (-38.20, -27.80)
[+1, +0] : ( +3.28, +20.72)  [+1, +1] : ( +8.15,  -6.60)  [+1, +2] : ( +9.79,  +3.76)  [+1, +3] : ( +1.64, +10.36)  [+1, +4] : ( -8.15,  +6.60)  [+1, +5] : ( -9.79,  -3.76)
[+2, +0] : (-24.93, +48.93)  [+2, +1] : (+27.42,  -1.44)  [+2, +2] : (+14.96, +23.03)  [+2, +3] : (-12.47, +24.47)  [+2, +4] : (-27.42,  +1.44)  [+2, +5] : (-14.96, -23.03)
[+3, +0] : (+48.93, -24.93)  [+3, +1] : (-23.03, -14.96)  [+3, +2] : ( +1.44, -27.42)  [+3, +3] : (+24.47, -12.47)  [+3, +4] : (+23.03, +14.96)  [+3, +5] : ( -1.44, +27.42)
[+4, +0] : (+20.72,  +3.28)  [+4, +1] : ( -3.76,  -9.79)  [+4, +2] : ( +6.60,  -8.15)  [+4, +3] : (+10.36,  +1.64)  [+4, +4] : ( +3.76,  +9.79)  [+4, +5] : ( -6.60,  +8.15)
hipfft outputs:
[+0, +0] : ( +7.00,  +7.00)  [+0, +1] : ( +8.00,  +8.00)  [+0, +2] : ( +9.00,  +9.00)  [+0, +3] : (+10.00, +10.00)  [+0, +4] : (+11.00, +11.00)  [+0, +5] : ( +0.00,  +0.00)
[+1, +0] : ( +1.00,  +1.00)  [+1, +1] : ( +2.00,  +2.00)  [+1, +2] : ( +3.00,  +3.00)  [+1, +3] : ( +4.00,  +4.00)  [+1, +4] : ( +5.00,  +5.00)  [+1, +5] : ( +6.00,  +6.00)
[+2, +0] : ( +7.00,  +7.00)  [+2, +1] : ( +8.00,  +8.00)  [+2, +2] : ( +9.00,  +9.00)  [+2, +3] : (+10.00, +10.00)  [+2, +4] : (+11.00, +11.00)  [+2, +5] : ( +0.00,  +0.00)
[+3, +0] : ( +1.00,  +1.00)  [+3, +1] : ( +2.00,  +2.00)  [+3, +2] : ( +3.00,  +3.00)  [+3, +3] : ( +4.00,  +4.00)  [+3, +4] : ( +5.00,  +5.00)  [+3, +5] : ( +6.00,  +6.00)
[+4, +0] : ( +7.00,  +7.00)  [+4, +1] : ( +8.00,  +8.00)  [+4, +2] : ( +9.00,  +9.00)  [+4, +3] : (+10.00, +10.00)  [+4, +4] : (+11.00, +11.00)  [+4, +5] : ( +0.00,  +0.00)

### How to reproduce
-  
hipcc -I/opt/rocm/include -I/work/home/wangzh/relionrocm/external/fftw/include -L/work/home/wangzh/relionrocm/external/fftw/lib  -lfftw3  -lrocfft  hip2fft.hip.cpp

### Environment

| Software | version |
|-----|-----|
| HIP version |: 1.5.18353 |

**Comment by holyprince** [comment]
Thank you for your help @malcolmroberts , but I am very confused and looked at the issue just remove some if-statement in plan.cpp. 
Can you tell me the reason and I can change some code on my machine? Because I apply the change of plan.cpp in my rocfft code and rebuild, the problem still exists.
Maybe I do not use the updated version of rocFFT, I use the rocfft version is 0.8.6 and the rocm version is 1.9.211. 
Thank you very much again!

**Comment by malcolmroberts** [comment]
The problem which caused the error is that I added code to check that in-place transforms had the same strides, distances, and offsets at a point in the program where these had not been set; thus, the setup phase returned an error, no plan was created, and thus no transform was performed.  Removing this check solved this issue.  We're going to make sure that this kind of behaviour will be caught by the test suite.

For your issue with 0.8.6, I'm not sure how this could be caused by this error, as 0.8.6 is from 2018, and the change that caused issue 195 is only weeks old.  I suspect that you may have some other version of rocFFT that is being used in your test.
