### ISSUE TITLE
Library implementation suggestions

### ISSUE THREAD

**Issue by bragadeesh** [ROCmSoftwarePlatform/rocFFT#2]
Using this to record all ideas for a good library implementation

**Comment by preda** [comment]
In his paper "Supercomputer-style FFT library for Apple G4" (link below), Richard Crandall presents an API proposal for an FFT library, comprising:

1) Complex FFT;
2) Real-signal FFT;
3) Inverse FFTs of the above;
4) Complex cyclic convolution;
5) Real-signal cyclic convolution;
6) 2-dimensional complex FFT;
7) 2-dimensional real-signal FFT;
8) Inverse FFTs for these 2-dimensional cases;
9) 2-dimensional complex convolution;
10) 2-dimensional real-signal convolution.

Offering "convolution" as an API primitive offers important optimization opportunities, for example by keeping the intermediary fft-transformed data in a transposed representation (saving transpose operations), and by merging multiple steps in a single kernel when possible (saving global memory round-trips).

https://pdfs.semanticscholar.org/25e3/6f4bdb1298416813ca3beaaf5f4b49105501.pdf?_ga=2.110805581.976118015.1512954370-353035247.1512954370

**Comment by doctorcolinsmith** [comment]
Closing due to no new activity.
