### ISSUE TITLE
Large Sizes Segfault

### ISSUE THREAD

**Issue by dockludge** [ROCmSoftwarePlatform/rocFFT#256]
### What is the expected behavior
No crash

### What actually happens
Segfault with:
```
#0  0x00007f636fcdbc6f in TransformPowX(ExecPlan const&, void**, void**, rocfft_execution_info_t*) () from /opt/rocm/lib/librocfft.so.0
#1  0x00007f636fcd42cd in rocfft_execute () from /opt/rocm/lib/librocfft.so.0
```
### How to reproduce
Take FFT example from here: https://rocfft.readthedocs.io/en/latest/library.html#example. Change N to 8192, and compile/run.

### Environment
| Hardware | description |
GPU
  Name:                    gfx906
  Marketing Name:          Vega 20
  Vendor Name:             AMD

CPU:
 Name:                    Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz

| Software | version |

|-----|-----|
| ROCK | 2.7.22 |
| ROCR | 1.1.9-99-g835b876 |
| HCC | 2.7.19315 |
| Library | 0.9.5.697-rocm-rel-2.7-22-ed7760e |

**Comment by malcolmroberts** [comment]
Hello; thanks for the report.

I think that this may have to do with the fact that some larger problem sizes use work memory; this isn't provided in the example code.  Could you try looking at the examples in

https://github.com/ROCmSoftwarePlatform/rocFFT/tree/develop/docs/samples

and see if you still have an issue?

**Comment by dockludge** [comment]
> Hello; thanks for the report.
> 
> I think that this may have to do with the fact that some larger problem sizes use work memory; this isn't provided in the example code. Could you try looking at the examples in
> 
> https://github.com/ROCmSoftwarePlatform/rocFFT/tree/develop/docs/samples
> 
> and see if you still have an issue?

Hi @malcolmroberts, that worked, thanks! I switched to the first sample and I could use larger sizes. On a side note, do you expect this library to be on par with cuFFT for most sizes? I tried a very large FFT size + batch (2^18 with batch of 100), and it's about 2x slower when I account for the fact that my Radeon VII has about 75% of the cores the V100 does.

**Comment by malcolmroberts** [comment]
Glad that worked!

We have done some work on performance analysis, and large 1D sizes is a target.  We have some ideas, so stay tuned!  But our goal isn't to be only just as fast as cuFFT.  ;)
