### ISSUE TITLE
Not able to install on SLES15.1 using install.sh

### ISSUE THREAD

**Issue by adilad** [ROCmSoftwarePlatform/rocFFT#259]
### What is the expected behavior
-  Retrieving: libcxxtools9-2.2.1-11.1.x86_64.rpm ......................................................................................................................................................................................................................[not found]
File './x86_64/libcxxtools9-2.2.1-11.1.x86_64.rpm' not found on medium 'http://download.opensuse.org/repositories/server:/http/SLE_15/'
Abort, retry, ignore? [a/r/i/...? shows all options] (a): a
Problem occurred during or after installation or removal of packages:
Installation has been aborted as directed.

### What actually happens
-  The package is not found

### How to reproduce
-  Run the install.sh script on SLES system

### Environment
| Hardware | description |
|-----|-----|
| GPU | device string |
| CPU | device string |

| Software | version |
|-----|-----|
| ROCK | v0.0 |
| ROCR | v0.0 |
| HCC | v0.0 |
| Library | v0.0 |

**Comment by adilad** [comment]
the repo seemed corrupted. I was able to work it out.

**Comment by malcolmroberts** [comment]
Glad you were able to work it out.

If all else fails, falling back to the cmake script is probably a good idea.
