### ISSUE TITLE
Cannot Compile for NVIDIA

### ISSUE THREAD

**Issue by tsjordan-eng** [ROCmSoftwarePlatform/rocFFT#271]
### What is the expected behavior
- follow build instructions
- successful build

### What actually happens
-  nvcc can't handle `std=c++1y`

### How to reproduce
- build:
   `mkdir build && CD build && cmake ..`  
   `CXX=hipcc make`
### Environment
- RHEL 7.7
- cuda 10.2 
- HIP_PLATFORM=nvcc

| Hardware | description |
|-----|-----|
| GPU |  Quadro M4000 |
| CPU | Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz |

| Software | version |
|-----|-----|
| ROCK |N/A |
| ROCR | N/A |
| HCC |  2.8.19361-cbe6b65e  |
| Library |  rocfft.x86_64 0:0.9.7.722_rocm_rel_2.9_6_e3055e1-1 |

**Comment by feizheng10** [comment]
The rocFFT build for NVIDIA platform was broken for a while, and under our todo list.
Could you please let us to know why you are interested in this?

**Comment by tsjordan-eng** [comment]
First, I wanted to compile my project with rocFFT, but I hit an error with that compilation:
```
/opt/rocm/include/hipfft.h:69:5: error: redeclaration of ‘MAJOR_VERSION’
...
/usr/local/cuda/include/library_types.h:75:2: note: previous declaration ‘libraryPropertyType_t MAJOR_VERSION’
```
This seemed to have been solved by commit 185001f. The RHEL repo only has version 2.9 while that commit is on 2.10. Because of this I'm trying to compile my own.

**Comment by feizheng10** [comment]
The new release 2.10 should be available within 1-2 days.

**Comment by tsjordan-eng** [comment]
I can wait the few days. I hope that's the only error I hit. Any work-arounds in the meantime?

**Comment by feizheng10** [comment]
> I can wait the few days. I hope that's the only error I hit. Any work-arounds in the meantime?

As what your found in commit 185001f, it should not be hard to apply it if you could build from source.

**Comment by tsjordan-eng** [comment]
My thoughts exactly. Is there a way I can get notified when the new version is out?

**Comment by feizheng10** [comment]
Don't know a simple way yet. However, you might see the latest announcement on https://github.com/RadeonOpenCompute/ROCm.
Anyway, I will post here for your convenience this time.

**Comment by feizheng10** [comment]
@tsjordan-eng , you should be able to check the new release:
 https://github.com/RadeonOpenCompute/ROCm
 http://repo.radeon.com/rocm/apt/debian/ 
 http://repo.radeon.com/rocm/yum/rpm/
 http://repo.radeon.com/rocm/zyp/zypper/

**Comment by feizheng10** [comment]
Please check the commit https://github.com/ROCmSoftwarePlatform/rocFFT/commit/828de1a887794218bb8bae922b882f8a922495f6

**Comment by malcolmroberts** [comment]
This should work now with the clang cuda compiler.  This isn't an officially supported compile path, so use at your own risk.
