### ISSUE TITLE
hipfft* functions don't call associated cufft* functions

### ISSUE THREAD

**Issue by tsjordan-eng** [ROCmSoftwarePlatform/rocFFT#272]
### What is the expected behavior
-  Using `hipfft*` with the nvidia compiler should result in compiling `cufft*` functions

### What actually happens
-  I get the following errors on the linking step
   ```
   undefined reference to `hipblasCreate'
   undefined reference to `hipblasDestroy
   undefined reference to `hipblasSscal'
   undefined reference to `hipfftDestroy'
   undefined reference to `hipfftExecC2C'
   undefined reference to `hipfftPlan1d'
   ```

### How to reproduce
-  Compile a program containing one of the above functions with `HIP_PLATFORM=nvcc`

### Environment
| Hardware | description |
|-----|-----|
| GPU |  Quadro M4000 |
| CPU | Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz |

| Software | version |
|-----|-----|
| ROCK |N/A |
| ROCR | N/A |
| HCC |  2.8.19361-cbe6b65e  |
| Library |  rocfft.x86_64 0:0.9.7.722_rocm_rel_2.9_6_e3055e1-1 |

### Guesses
Is there supposed to be a translation entry in the [HIP repo](https://github.com/ROCm-Developer-Tools/HIP/blob/master/include/hip/nvcc_detail/hip_runtime_api.h#L182) for these items? I see that they are supported in the [HIP repo](https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/CUFFT_API_supported_by_HIP.md), but I don't see it in the code.

**Comment by feizheng10** [comment]
Yes and no. The HIP repo you point is the support list on HIP language runtime API level. 
hipBlas and hipFFT have their own support list(We don't have a published page yet).
hipBlas issue should report on hipBlas page. I checked with my co-worker, the hipBlas should be able to build on NV platform.
Again, we hasn't address hipFFT/rocFFT build on NV platform. Will let you know ASAP.

Anyway, some suggestions to isolate your problems:
- try small cases only link to hipBlas or hipFFT lib

- check the symbols in *.so with nm or readelf

-  manipulate RPATH

**Comment by tsjordan-eng** [comment]
So to clarify, should both the hipBLAS and hipFFT packages have interface functions to cuBLAS AND cuFFT respectively as well as ROC conditionally?

**Comment by feizheng10** [comment]
hipBLAS is a wrapper of cuBLAS on NV platform and rocBLAS on AMD platform. So if you run hipBLAS on NV platform, you should be able to go. If you run hipBLAS on AMD platform, there might be some functions not implemented yet.
Currently, hipFFT is the wrapper only for rocFFT. We could make hipFFT like hipBLAS, in which just a wrapper of cuFFT and rocFFT.

**Comment by tsjordan-eng** [comment]
Ah! Okay. Would it be beneficial for me to make a little header file that conditionally #Defines the appropriate cuda functions according to [this](https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/CUFFT_API_supported_by_HIP.md) and modeled after [this] (https://github.com/ROCm-Developer-Tools/HIP/blob/master/include/hip/nvcc_detail/hip_runtime_api.h) or [this] (https://github.com/ROCmSoftwarePlatform/hipBLAS/blob/develop/library/src/nvcc_detail/hipblas.cpp)? Should that be in a new project called hipFFT?

I'm sorry for the misunderstanding. When I read the main HIP README I thought all of this had been done already and I could just immediately port my code.

**Comment by feizheng10** [comment]
hipFFT header + hipfy tool is one way for porting.
Conditional defined header file is another way, but it should not been called hipFFT.

**Comment by dmcdougall** [comment]
One of the Cray/HPE folks just told me this was sitting.  Sorry for the delay.

I’ll chase this up internally for you.

**Comment by feizheng10** [comment]
We are working on  the marshalling hipFFT library, and it should be ready within a couple days.

**Comment by txomin13** [comment]
What is the current status of this issue?

**Comment by malcolmroberts** [comment]
These functions should be working in the new hipFFT repo, with the exception of the 64-bit plan functions.
