### ISSUE TITLE
Out-of-place operation failure in 3D C2C case

### ISSUE THREAD

**Issue by ekuznetsov139** [ROCmSoftwarePlatform/rocFFT#282]
I am investigating a mismatch in the fft operation in tensorflow-rocm. Tracing the failure brings me to rocFFT. The observed behavior is as follows.

* A plan is created via a call to hipfftMakePlanMany.
* hipfftExecC2C is invoked with the understanding that the operation is going to be out-of-place (arguments idata and odata are different).
* It produces garbled data.

I got rocFFT to dump the plan, and it looks as follows 

Work buffer size: 64
Work buffer ratio: 1

scheme: CS_3D_RTRT
dimension: 3
batch: 1
length: 4 4 4 
iStrides: 1 4 16 
oStrides: 1 4 16 
iOffset: 0
oOffset: 0
iDist: 64
oDist: 64
direction: -1
not inplace
array type: complex interleaved -> complex interleaved
TTD: 0
large1D: 0
lengthBlue: 0
OB_USER_OUT -> OB_USER_OUT
B -> B

    scheme: CS_2D_RTRT
    dimension: 2
    batch: 1
    length: 4 4 4 
    iStrides: 1 4 16 
    oStrides: 1 4 16 
    iOffset: 0
    oOffset: 0
    iDist: 64
    oDist: 64
    direction: -1
    inplace
    array type: complex interleaved -> complex interleaved
    TTD: 0
    large1D: 0
    lengthBlue: 0
    OB_USER_OUT -> OB_USER_OUT
    B -> B

        scheme: CS_KERNEL_STOCKHAM
        dimension: 1
        batch: 1
        length: 4 4 4 
        iStrides: 1 4 16 
        oStrides: 1 4 16 
        iOffset: 0
        oOffset: 0
        iDist: 64
        oDist: 64
        direction: -1
        inplace
        array type: complex interleaved -> complex interleaved
        TTD: 0
        large1D: 0
        lengthBlue: 0
        OB_USER_OUT -> OB_USER_OUT
        B -> B

        scheme: CS_KERNEL_TRANSPOSE
        dimension: 2
        batch: 1
        length: 4 4 4 
        iStrides: 1 4 16 
        oStrides: 1 4 16 
        iOffset: 0
        oOffset: 0
        iDist: 64
        oDist: 64
        direction: -1
        not inplace
        array type: complex interleaved -> complex interleaved
        TTD: 0
        large1D: 0
        lengthBlue: 0
        OB_USER_OUT -> OB_TEMP
        B -> T

        scheme: CS_KERNEL_STOCKHAM
        dimension: 1
        batch: 1
        length: 4 4 4 
        iStrides: 1 4 16 
        oStrides: 1 4 16 
        iOffset: 0
        oOffset: 0
        iDist: 64
        oDist: 64
        direction: -1
        inplace
        array type: complex interleaved -> complex interleaved
        TTD: 0
        large1D: 0
        lengthBlue: 0
        OB_TEMP -> OB_TEMP
        T -> T

        scheme: CS_KERNEL_TRANSPOSE
        dimension: 2
        batch: 1
        length: 4 4 4 
        iStrides: 1 4 16 
        oStrides: 1 4 16 
        iOffset: 0
        oOffset: 0
        iDist: 64
        oDist: 64
        direction: -1
        not inplace
        array type: complex interleaved -> complex interleaved
        TTD: 0
        large1D: 0
        lengthBlue: 0
        OB_TEMP -> OB_USER_OUT
        T -> B

    scheme: CS_KERNEL_TRANSPOSE_XY_Z
    dimension: 2
    batch: 1
    length: 4 4 4 
    iStrides: 1 4 16 
    oStrides: 1 4 16 
    iOffset: 0
    oOffset: 0
    iDist: 64
    oDist: 64
    direction: -1
    not inplace
    array type: complex interleaved -> complex interleaved
    TTD: 0
    large1D: 0
    lengthBlue: 0
    OB_USER_OUT -> OB_TEMP
    B -> T

    scheme: CS_KERNEL_STOCKHAM
    dimension: 1
    batch: 1
    length: 4 4 4 
    iStrides: 1 4 16 
    oStrides: 1 4 16 
    iOffset: 0
    oOffset: 0
    iDist: 64
    oDist: 64
    direction: -1
    inplace
    array type: complex interleaved -> complex interleaved
    TTD: 0
    large1D: 0
    lengthBlue: 0
    OB_TEMP -> OB_TEMP
    T -> T

    scheme: CS_KERNEL_TRANSPOSE_Z_XY
    dimension: 2
    batch: 1
    length: 4 4 4 
    iStrides: 1 4 16 
    oStrides: 1 4 16 
    iOffset: 0
    oOffset: 0
    iDist: 64
    oDist: 64
    direction: -1
    not inplace
    array type: complex interleaved -> complex interleaved
    TTD: 0
    large1D: 0
    lengthBlue: 0
    OB_TEMP -> OB_USER_OUT
    T -> B

There is a notable absence of any mentions of OB_USER_IN. A test confirmed that rocFFT ignores the input buffer entirely and processes the output buffer inplace (so, if I copy the input data into the output buffer by hand before calling hipfftExecC2C, it does work and it does produce the correct results.)

**Comment by ekuznetsov139** [comment]
Nevermind, I see it's already known (#270)

**Comment by malcolmroberts** [comment]
This may be fixed; I'm unable to reproduce this with the latest version of develop; I'm not sure which commit fixed it though.  Would you mind giving it a try?

**Comment by ekuznetsov139** [comment]
It looks like this particular issue is fixed. 

However, I'm seeing failures in a number of tests that used to pass with 3.0 (so the total number of failures is actually higher now than before)...

**Comment by malcolmroberts** [comment]
See https://github.com/ROCmSoftwarePlatform/rocFFT/issues/283; there are some compilation issues with 3.0.
