### ISSUE TITLE
Build fails with compiler error on rocm 3.0

### ISSUE THREAD

**Issue by malcolmroberts** [ROCmSoftwarePlatform/rocFFT#283]
When compiling with hcc, via, for example,
```
cmake -DCMAKE_CXX_COMPILER=hcc ..
```
the compilation fails with some stack trace errors in '/opt/rocm/hcc/bin/clang-10'.

**Comment by ekuznetsov139** [comment]
clang from 3.0 needs up to 15 GB of RAM to compile each individual kernel source file (and multiple instances of clang can easily exhaust the system memory).

Attached patch seems to resolve its problems (though I can't say why).

[clang_oom.txt](https://github.com/ROCmSoftwarePlatform/rocFFT/files/4007957/clang_oom.txt)
