### ISSUE TITLE
Incorrect result with 2D C2R FFT

### ISSUE THREAD

**Issue by ekuznetsov139** [ROCmSoftwarePlatform/rocFFT#287]
See attachment.

[fft_test.zip](https://github.com/ROCmSoftwarePlatform/rocFFT/files/4015625/fft_test.zip)

Input:
[[0, 1, 2]
[3, 4, 5]
[6, 7, 8]
[9, 0, 1]]

Both numpy and fftw3 produce the output
[[58, 2, 10, 2]
[-24, -8, 0, 8]
[6, -10, -10, -10]
[-24, 8, 0, -8]]

rocfft produces the output
[[58, 2, 10, 2]
[-14, -10, 10, 6]
[6, -10, -10, -10]
[-34, 10, -10, -6]]

**Comment by malcolmroberts** [comment]
Thanks for adding the test code.

The FFTW plan is c2r, as is the hip plan (HIPFFT_C2R).  This implies that the input is complex with Hermitian symmetry.  In addition the the DC and Nyquist frequencies being real-valued, one also needs that other values be complex conjugates of each other.  Taking your input and imposing Hermitian symmetry, we get

```
[[0, 1, 2]
[3, 4, 5]
[6, 7, 8]
[3, 0, 5]]
```
and the outputs agree.
