### ISSUE TITLE
Can't build for HIP

### ISSUE THREAD

**Issue by Lucretia** [ROCmSoftwarePlatform/rocFFT#290]
### What is the expected behavior
-  That it builds

All output reported here https://github.com/justxi/rocm/issues/132

### What actually happens
-  I get errors

### How to reproduce
-  Try to build

### Environment
| Hardware | description |
|-----|-----|
| GPU | Hawaii PRO [Radeon R9 290/390] |
| CPU | AMD FX(tm)-8350 Eight-Core Processor |

| Software | version |
|-----|-----|
| ROCK | No idea, kernel 5.6.0-rc1 |
| ROCR | v3.0.0 |
| HCC | v3.0.0 |
| Library | v3.0.0 |

**Comment by feizheng10** [comment]
First, I believe we don't officially support gfx701 anymore.
Second, from the build command, it looks like you are build with hip-clang. Could you let us to know why? Is it possible just build with hcc(remove -DHIP_PLATFORM=hip-clang -DUSE_HIP_CLANG=ON -DHIP_COMPILER=clang)?

**Comment by Lucretia** [comment]
Well, given AMD have said that HCC is deprecated and HIP is the future I was trying to build it.

Also, LLVM still supports gfx7 targets.

**Comment by feizheng10** [comment]
HCC is not fully deprecated yet. And you should be able to work with it.
Alternatively, if you still want to go for hip-clang,  I would suggest to try at least on gfx803.

**Comment by Lucretia** [comment]
Well, I don't have that card, I don't have access to pci atomics either and again, can't upgrade yet, llvm supports gfx7 gcn.

**Comment by feizheng10** [comment]
Well, it more looks like a hip-clang build issue. I will have my co-worker to have a look and back to you.

**Comment by feizheng10** [comment]
So, this is not a specific issue for rocFFT.
Checked with staff with other teams, "the gfx701 won't be supported by the latest runtime library and hip-clang compiler".
Sorry for the inconvenience.

**Comment by Lucretia** [comment]
Firstly it doesn't build no matter what, I already said that.

Surely, just building it with the target set to gfx7 should be ok? The backend supports it.

**Comment by feizheng10** [comment]
Not sure about that.
You might post on https://github.com/ROCm-Developer-Tools/HIP.

**Comment by malcolmroberts** [comment]
The build system has changed quite a bit since there was last any activity on this issue.  I'm going to close; please re-open if this is still unresolved.
