### ISSUE TITLE
result of large 1D FFT with stride not equal 1 is not  correct

### ISSUE THREAD

**Issue by hoptony** [ROCmSoftwarePlatform/rocFFT#301]
### What is the expected behavior
-  The input dataset is N rows, 2 cols，I want to perform 1-D length N FFT  transform on each     column.
    I construct the dataset, when N = 2048, the result is correct,like below:
    batch = 0
    [0 0] [2048.000000  0.000000 ]
    just one data's real part = N, others are zero;
   this is the correct behavior.

### What actually happens
-  when N = 4096 or larger, the result is not correct and almost every data is not zero, unlike the correct behavior.

### How to reproduce
-  The test case likes below:
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <assert.h>
#include "hip/hip_runtime_api.h"
#include "rocfft.h"

#define pi 3.1415926535897932385
#define EPISION (1.0e-12)

int main(int argc, char *argv[])
{
	rocfft_setup();
	size_t N_row = 4096;
	size_t N_col = 2 ;

	if (argc>1) N_row = atoi(argv[1]);
	if (argc>2) N_col = atoi(argv[2]);

	size_t Nbytes = (size_t) N_row * sizeof(double) * 2 * N_col;
	double * inx;
	double * inx_trans;
	double * outx;
	double * outx_trans;
	double * outx_trans2;
	double * dcux;
	double * dcux_trans;
	double tmp;
	hipError_t herr;

	herr = hipHostMalloc(&inx, Nbytes);
	herr = hipHostMalloc(&inx_trans, Nbytes);
	if(herr != 0) 
		printf("something wrong in hipHostMalloc...\n");

	herr = hipHostMalloc(&outx, Nbytes);
	herr = hipHostMalloc(&outx_trans, Nbytes);
	herr = hipHostMalloc(&outx_trans2, Nbytes);
	if(herr != 0) 
		printf("something wrong in hipHostMalloc...\n");

	herr = hipMalloc(&dcux, Nbytes);
	herr = hipMalloc(&dcux_trans, Nbytes);
	if(herr != 0) 
		printf("something wrong in hipMalloc...\n");

	for (size_t j = 0; j < N_col; j++)
		for (size_t i = 0; i < N_row; i++)
		{
			tmp = 2.*j*i*pi/N_row;
			inx[2*i   + 2*j*N_row]  = cos(tmp);
			inx[2*i+1 + 2*j*N_row]  = sin(tmp);

		}
    for (size_t j = 0; j < N_col; j++)
		for (size_t i = 0; i < N_row; i++)
		{
			inx_trans[2*j   + 2*i*N_col]  = inx[2*i+2*j*N_row];
			inx_trans[2*j+1 + 2*i*N_col]  = inx[2*i+1+2*j*N_row];

		}
    
	hipMemcpy(dcux, inx, Nbytes, hipMemcpyHostToDevice);
	hipMemcpy(dcux_trans, inx_trans, Nbytes, hipMemcpyHostToDevice);

	rocfft_plan planf = NULL;
	rocfft_plan planf_trans = NULL;
	rocfft_plan_description plan_descriptionf;
	rocfft_plan_description plan_descriptionf_trans;
	rocfft_status err_status = rocfft_status_success;
	
	size_t length = N_row;
//	size_t *ioffsets, *ooffsets, value=0, istride=1, ostride=1, dimens=1, idist=1, odist=1;
	size_t *ioffsets, *ooffsets, value = 0, istride = 2 , ostride = 2, dimens = 1, idist = length, odist = length;
	ioffsets = &value;
	ooffsets = &value;
	size_t num_of_transforms = 1;
	// perform a 1D FFT along columns, eg: 4096rows * 2cols, two batchs of 4096 points FFT
	err_status = rocfft_plan_description_create(&plan_descriptionf_trans);
	assert(err_status == rocfft_status_success);
    err_status = rocfft_plan_description_set_data_layout(plan_descriptionf_trans,rocfft_array_type_complex_interleaved,rocfft_array_type_complex_interleaved,ioffsets,ooffsets,dimens,&istride,idist,dimens,&ostride,odist);
	assert(err_status == rocfft_status_success);

	err_status = rocfft_plan_create(&planf_trans, rocfft_placement_inplace, rocfft_transform_type_complex_forward, rocfft_precision_double,1, &length, num_of_transforms, plan_descriptionf_trans);
	assert(err_status == rocfft_status_success);
	err_status = rocfft_plan_get_print(planf_trans);
	assert(err_status == rocfft_status_success);

	rocfft_execution_info info_trans = NULL;		
	err_status = rocfft_execution_info_create(&info_trans);
	assert(err_status == rocfft_status_success);
	size_t fbuffersize_trans = 0;
	err_status =  rocfft_plan_get_work_buffer_size(planf_trans, &fbuffersize_trans);
	assert(err_status == rocfft_status_success);
	void* fbuffer_trans = NULL;
	hipMalloc(&fbuffer_trans, fbuffersize_trans);
	err_status = rocfft_execution_info_set_work_buffer(info_trans, fbuffer_trans, fbuffersize_trans);
	assert(err_status == rocfft_status_success);

	rocfft_execute(planf_trans, (void **) &dcux_trans, NULL, info_trans);
	hipMemcpy(outx_trans,dcux_trans, Nbytes, hipMemcpyDeviceToHost);
	hipDeviceSynchronize();

	// result test
	// for (size_t j = 0; j < N_col; j++) {
	{ size_t j = 0;
          printf("batch = %ld\n",j);
          for (size_t i = 0; i < N_row; i++) {
                  // tmp = abs(outx_trans[2*i+j*2*N])+abs(outx_trans[2*i+1+j*2*N]);
                  tmp = abs(outx_trans[2*j + i*2*N_col]) + abs(outx_trans[2*j+1 + i*2*N_col]);
                  if (tmp>EPISION){
                      // printf("[%ld %ld] (%.15f,%.15f)\n",j,i,outx_trans[2*i+j*2*N],outx_trans[2*i+1+j*2*N]);
                      printf("[%ld %ld] (%.15f %.15f)\n", j,i, outx_trans[2*j + i*2*N_col], outx_trans[2*j+1+i*2*N_col]);
                  }
          }
          printf("\n");
    }
	hipDeviceSynchronize();
	

	rocfft_execution_info_destroy(info_trans);
	rocfft_plan_description_destroy(plan_descriptionf_trans);
	rocfft_plan_destroy(planf_trans);
	rocfft_cleanup();
	
	hipFree(dcux);
	hipFree(dcux_trans);
	hipFree(fbuffer_trans);
	hipHostFree(inx);
	hipHostFree(inx_trans);
	hipHostFree(outx);
	hipHostFree(outx_trans);
	hipHostFree(outx_trans2);

	return 0;
}

### Environment

hardware 
GPU | AMD Radeon VII (Vega20)
CPU | AMD Ryzen 5 3600X

Software | version
ROCK | v3.5.0
ROCR | v3.5.0
HIPHCC-ROCCLR | v3.5.0
ROCFFT | v3.5.0

**Comment by evetsso** [comment]
Can you provide some detail?  What specific size of FFT did you try, and with what stride?

**Comment by hoptony** [comment]
> 
> 
> Can you provide some detail? What specific size of FFT did you try, and with what stride?

Sorry, My question is a little slow to update.  I checked my code and I am confused at this question for a few days.

**Comment by feizheng10** [comment]
This should be a known issue. Will back to you soon.

**Comment by hoptony** [comment]
> 
> 
> This should be a known issue. Will back to you soon.

Is this a bug that still exists so far?

**Comment by feizheng10** [comment]
@hoptony Here is a quick patch, https://github.com/ROCmSoftwarePlatform/rocFFT/tree/1d_fix
Could you have a quick try on your side?

**Comment by hoptony** [comment]
> 
> 
> @hoptony Here is a quick patch, https://github.com/ROCmSoftwarePlatform/rocFFT/tree/1d_fix
> Could you have a quick try on your side?

Thank you, I'll test and verify.

**Comment by malcolmroberts** [comment]
I think that the parameters would be something like

rocfft-rider --length 4096  -b 2 --istride 2 --ostride 2

which has since been fixed in rocFFT.  Please re-open if this is still an issue.
