### ISSUE TITLE
transform type determined in execution phase

### ISSUE THREAD

**Issue by yuxianglin** [ROCmSoftwarePlatform/rocFFT#307]
-  In rocfft, the transform direction (forward or backward) is determined in the plan creation, I wonder can we first create a plan without setting the direction, and determine the directory in the execution phase? Because in my application I have multiple forward and backward, I don't want to create multiple plan for each of them.

Any advice would be appreciated.

Yuxiang

**Comment by malcolmroberts** [comment]
I'm afraid that you'll have to create a plan for each direction.  Plans are pretty cheap to create; this shouldn't be a lot of overhead.
