### ISSUE TITLE
Allow specifying `-DAMDGPU_TARGETS`

### ISSUE THREAD

**Issue by riaqn** [ROCmSoftwarePlatform/rocFFT#340]
We have similar things for rocblas and rocsparse. It speeds up the compilation process if I have only one GPU.

**Comment by evetsso** [comment]
Can you clarify your request?  AMDGPU_TARGETS is already accepted as a CMake parameter.

https://github.com/ROCmSoftwarePlatform/rocFFT/blob/069dff719152196c3d004bb8cec7cbe96907e2c2/CMakeLists.txt#L185

As a cache variable, the value can be overridden when CMake is run.

**Comment by riaqn** [comment]
@evetsso Thank you for the reply - yes it was my mistake. I had this wrong impression because it was not in `install.sh`
