### ISSUE TITLE
real_post_process_kernel_transpose, an offset looks like out-of-memory

### ISSUE THREAD

**Issue by vasslavich** [ROCmSoftwarePlatform/rocFFT#347]
Hello!
I'm using rocFFT, 3D inplace transform of real to complex. 
In the rocprof output I see, it results to six kernels. 
I have a question about algorithm in the second kernel, _real_post_process_kernel_transpose_, line:
https://github.com/ROCmSoftwarePlatform/rocFFT/blob/d17a8f8f6125b521d93ee1c751cf9fe669eb6d55/library/src/device/realcomplex_even_transpose.cpp#L43 

## First the all, my input:
---------------------------------------------------------------------

The dimensions of real input are: N1=N2=N3=1024. 

The input_lengths (real):
`std::vector<size_t> length = {1024, 1024, 1024};`

The output lengths (complex):
`std::vector<size_t> output_lengths = {1024, 1024, 513};`

The input strides (real, with a padding to the (1024/2 + 1) complex values): 
`std::vector<size_t> input_strides = {1, 1026, 1050624};`

The output strides (complex): 
`std::vector<size_t> output_strides = {1, 513, 525312};`

The total number of the input real elements:
`size_t num_of_real = 1024*1024*1024;`

The **total number of the output complex** elements:
`size_t num_of_complex = 1024*1024*(1024/2 + 1); //537919488`

The input size in bytes (with a padding to the number of the output complex elements): 
`size_t input_bytes = num_of_complex*8*2;  //= 8606711808`

Since inplace mode, output gpu pointer is the input one.

```
void *gpu_in = nullptr;
hipMalloc(&gpu_in, input_bytes);

void *gpu_out = gpu_in;

rocfft_plan_description gpu_description = nullptr;
rocfft_plan_description_create(&m_gpu_description);

rocfft_plan_description_set_data_layout(
            gpu_description,
            rocfft_array_type_real,
            rocfft_array_type_hermitian_interleaved,
            NULL,
            NULL,
            input_strides().size(),
            input_strides().data(),
            0,
            output_strides().size(),
            output_strides().data(),
            0);
			

rocfft_plan gpu_plan = nullptr;
rocfft_plan_create(&gpu_plan,
                    rocfft_placement_inplace,
                    rocfft_transform_type_real_forward,
                    rocfft_precision_double,
                    input_lengths.size(),
                    input_lengths.data(),
                    1,
                    gpu_description);
											   
											   
rocfft_execution_info planinfo = nullptr;
rocfft_execution_info_create(&planinfo);

void* m_wbuffer = nullptr;
size_t m_wbuffer_size = 0;
rocfft_plan_get_work_buffer_size(gpu_plan, &m_wbuffer_size);
if(m_wbuffer_size){ ... }

rocfft_execute(
            gpu_plan,
            gpu_in,
            gpu_out, 
            planinfo);
```
			
## The question:
-----------------------------------------------------------

In the kernel, I see https://github.com/ROCmSoftwarePlatform/rocFFT/blob/d17a8f8f6125b521d93ee1c751cf9fe669eb6d55/library/src/device/realcomplex_even_transpose.cpp#L59
`size_t input_batch_start  = idist * blockIdx.z;`

I had printed the values of idist and odist, before kernel was called https://github.com/ROCmSoftwarePlatform/rocFFT/blob/d17a8f8f6125b521d93ee1c751cf9fe669eb6d55/library/src/device/realcomplex_even_transpose.cpp#L210  
They are equal to **537919488**. I'm confused, they are equal to the total number (see above) of the output complex values, `num_of_complex`.
_input_batch_start_ and _output_batch_start_ will be state to the same value, **537919488**. 

I see, `Handler<T_O, cbtype>::write(offset, ....)` with:
**offset** > (the total number (see above) of the output complex values, **num_of_complex**, in out_gpu).
Will this write to out-of-memory? I've done some tests, I have worry that it is.

Maybe, my code includes an error somewhere.
Maybe, the calculation of input_batch_start and output_batch_start  could be like this:
```
size_t input_batch_start  = idist * (blockIdx.z - 1);
size_t output_batch_start = odist * (blockIdx.z - 1);
```

**Comment by evetsso** [comment]
For that kernel, `blockIdx.z` is the index of the transform, and counts from 0.  So if the `number_of_transforms` parameter to `rocfft_plan_create` is 1, then for that kernel `blockIdx.z` will always be 0 and `idist` (which is the distance between input transforms) will be effectively unused.

If possible, it would be good for you to test on the develop branch, in case there was a problem that has since been fixed.  You did not state which version of rocFFT you were testing, but there have been some changes in the somewhat recent past in this area that could help.

I believe that answers your question, so I will close this issue.  Please feel free to reopen it if this does not answer your question, or you have additional concerns.

**Comment by vasslavich** [comment]
Hello, @evetsso ! Thank you for you quick response! 
Oh, I'm sorry, exactly, the blockIdx dimensions are zero-based!  I'm being upsetted with myself!

Thanks!
