### ISSUE TITLE
Why is the difference in the inverse forward transform FFT(IFFT(X)) ?

### ISSUE THREAD

**Issue by vasslavich** [ROCmSoftwarePlatform/rocFFT#352]
Hello, dear colleagues!

**rocFFT develop/341b969**

I've attached the source file _rocfft_example_realcomplex.cpp_
This is based on an example from _/clients/samples/rocfft/rocfft_example_realcomplex.cpp_.

**I have a problem**:
1. I use two consecutive transformations: IN(complex) -> IFFT  -> FFT -> OUT. The IN is being generated by the function https://github.com/ROCmSoftwarePlatform/rocFFT/blob/341b9695fe25ac9a9cd99ef12c01e86515711e32/clients/samples/rocfft/examplekernels.h#L466  As it doing in the source example _/clients/samples/rocfft/rocfft_example_realcomplex.cpp_
3. I have the difference in the IN and OUT complex values.

There are small changes here:
- the loop with strides of real values' rows, https://github.com/ROCmSoftwarePlatform/rocFFT/blob/341b9695fe25ac9a9cd99ef12c01e86515711e32/clients/samples/rocfft/rocfft_example_realcomplex.cpp#L77
- move the main code to class function _compute()_
- a check with a _backward_ transform added

**Run test IN(real) ->FFT->IFFT->OUT(real): diff(IN,OUT) OK**:
- CLI
`$ app --device 0 --check-backward on --length 512 512 512`
- The diff is OK
`$ diff percent max(r2c): 0.000000e+00: 0/134217728, -1.832551e-06, -1.832551e-06`

**Run test IN(complex) -> IFFT->FFT->OUT(complex) : diff(IN,OUT) FAIL**:
- CLI
`$ app --device 0 --inverse --check-backward on --length 512 512 512`
- The diff is FAIL
 `$ diff percent max(c2r): 1.000000e+02: 5199623, -2.459608e+02:-2.459608e+02, 3.979039e-13:1.278977e-13`

if someone has ideas, please.
Thanks!
[rocfft_example_realcomplex.txt](https://github.com/ROCmSoftwarePlatform/rocFFT/files/8333291/rocfft_example_realcomplex.txt)

**Comment by vasslavich** [comment]
Hi @malcolmroberts! Thanks yout for the reply! 
I've been thinking about the code and unfortunately I still don't see where the wrong length is passed.
With `$ app --device 0 --inverse --check-backward on --length 4 4 4`  the logical length 4,4,4 is passed to the function `rocfft_plan_create`.

Perhaps something else?
Thanks!

**Comment by malcolmroberts** [comment]
Sorry; looks like I was misreading the log info.

I took a look at this, and it seems like the data initialization function isn't correct; it seems that there is some issue with the Hermitian symmetry imposer in our sample code.  For example, the output of a 3x3x3 real-to-complex transform looks like this:

```
GPU output:
(15.9117,0) (-0.726616,0.340871) 
(-0.21056,-0.656155) (1.02798,-0.815972) 
(-0.21056,0.656155) (-1.04546,0.929485) 

(1.01058,0.681157) (-0.626661,0.268047) 
(-0.499458,-0.64928) (-0.143732,-1.51836) 
(0.0994139,-0.0344952) (-0.626013,0.565439) 

(1.01058,-0.681157) (1.10769,-0.72861) 
(0.0994139,0.0344952) (0.292381,2.33971) 
(-0.499458,0.64928) (-0.206403,-0.427028) 
```

but the code input in your code looks like 
```
(1,0) (2,10) 
(1,11) (2,11) 
(1,-11) (2,12) 

(11,10) (12,10) 
(11,11) (12,11) 
(11,12) (12,12) 

(11,-10) (22,10) 
(21,11) (22,11) 
(11,-11) (22,12) 
```
In the r2c transform output, both (0.0994139,0.0344952) and its complex conjugate are present.  In the input for your test code, (21,11) and (11,12) should be complex conjugates, but they clearly aren't.  So our sample Hermitian-symmetric initializer isn't working correctly, and we should fix that.

**Comment by malcolmroberts** [comment]
Having non-Hermitian-symmetric input data means that the input is malformed.  For correct data, there shouldn't be any problem.  Also, if you just do a round trip, then the data is automatically in the correct format.

**Comment by vasslavich** [comment]
Thanks!
I found another strangeness. Updated file rocfft_example_realcomplex_2.txt (with some outputs) attached.
I give the test cli and the output of the diffs:

ok
`$ build/bench --device 0 --check-backward on --length 128 128 128`
`$ diff percent max(r2c): 7.105427e-13: 260/2097152, 2.000000e+00, 2.000000e+00`

ok
`$ build/bench --device 0 --check-backward on --length 128 128 64`
`$ diff percent max(r2c): 1.421085e-12: 16640/1048576, 1.000000e+00, 1.000000e+00`

ok
`$ build/bench --device 0 --check-backward on --length 512 512 512`
`$ diff percent max(r2c): 0.000000e+00: 0/134217728, -1.832551e-06, -1.832551e-06`

(!)
`$ build/bench --device 0 --check-backward on --length 1024 1024 1024`
`$ diff percent max(r2c): 1.999023e+02: 1538/1073741824, -1.832551e-06, 1.830761e-06`

(!)
`$ build/bench --device 0 --check-backward on --length 1024 1024 512`
`$ diff percent max(r2c): 1.999023e+02: 1538/536870912, -1.832551e-06, 1.830761e-06`

UPD:
[rocfft_example_realcomplex_2.txt](https://github.com/ROCmSoftwarePlatform/rocFFT/files/8342651/rocfft_example_realcomplex_2.txt)

**Comment by vasslavich** [comment]
UPD: A checking of hip return code was added
[rocfft_example_realcomplex_3.txt](https://github.com/ROCmSoftwarePlatform/rocFFT/files/8348954/rocfft_example_realcomplex_3.txt)

**Comment by malcolmroberts** [comment]
I think that this is solved, so I will close this issue.  Please feel free to re-open if needed.
