### ISSUE TITLE
The question about performance

### ISSUE THREAD

**Issue by vasslavich** [ROCmSoftwarePlatform/rocFFT#354]
Hello!
We are exploring the possibility of migrating from AI100 GPU to MI100. Benchmarks show that rocFFT has the performance potential on MI100 and we'd like to improve it if there is such a way. We use 3D with dimensions of sizes of 512-1024. 
We are wondering if rocFFT uses Cooley-Tukey for radix-2 or another algorithm? 
Thanks!

**Comment by feizheng10** [comment]
Currently, rocFFT takes Stockham for radix-2.
We would like to hear from you for any suggestions!

**Comment by vasslavich** [comment]
Hello, @feizheng10 , thank you for the reply!
Hmm, but the Stockham algorithm's data flow not comes from cache-awareness. I will share if any ideas.
