### ISSUE TITLE
Build of rocFFT fails

### ISSUE THREAD

**Issue by dipietrantonio** [ROCmSoftwarePlatform/rocFFT#363]
Hi All,

I am trying to build this library (and the whole ROCm) from source. I hit what it seems to be a programming error, I show the output below.

The exact version of rocFFT is 
```
ubuntu@cdp-rocmbuild:~/rocm-from-source/build/rocFFT$ git log
commit 15ac7c4a2ac7e045f27c8939b9ad2ff31ab88b62 (HEAD, tag: rocm-5.1.1, tag: rocm-5.1.0, rocm-swplat/release/rocm-rel-5.1, m/roc-5.1.x)
Author: Steve Leung <Steve.Leung@amd.com>
Date:   Mon Mar 14 22:12:15 2022 -0600

    tree_node_3D: use diagonal sbrc for gfx1030
```
and here is the error
```
Running command make -j 8 install
[  1%] Building C object library/src/CMakeFiles/sqlite3.dir/__/__/_deps/sqlite_local-src/sqlite3.c.o
[  2%] Building CXX object library/src/CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o
[  2%] Building CXX object library/src/CMakeFiles/rocfft_rtc_helper.dir/rtccompile.cpp.o
[  3%] Building CXX object library/src/device/generator/CMakeFiles/stockham_gen.dir/stockham_gen.cpp.o
In file included from /home/ubuntu/rocm-from-source/build/rocFFT/library/src/device/generator/stockham_gen.cpp:30:
In file included from /home/ubuntu/rocm-from-source/build/rocFFT/library/src/device/generator/stockham_gen_cc.h:22:
/home/ubuntu/rocm-from-source/build/rocFFT/library/src/device/generator/stockham_gen_base.h:92:30: error: use of undeclared identifier 'ceil'
            unsigned int n = ceil(double(length) / width / threads_per_transform) * width;
                             ^
/home/ubuntu/rocm-from-source/build/rocFFT/library/src/device/generator/stockham_gen_base.h:683:33: error: use of undeclared identifier 'floor'
        unsigned int  iheight = floor(height);
                                ^
```

**Comment by evetsso** [comment]
Hi @dipietrantonio , thanks for reporting this issue.

This has already been fixed in the `develop` branch with 31589ce749a7dc27158e98dcbfbb33ab0a288fa5, and will be present in the upcoming 5.2 ROCm release.

Are you able to cherry-pick that commit into your build, or build any of the `release/rocm-rel-5.2` or `develop` branches instead?

**Comment by dipietrantonio** [comment]
Hi @evetsso, thank you for your prompt reply. I am trying to build the whole ROCm stack from source for the Pawsey Supercomputing Centre in Australia. Currently I am only developing the installation script, if this issue has been fixed in the next release, then by the time I am finished this won't be a problem anymore :) but in case I need it, I will cherrypick the commit. Thank you again, keep up with the good work!

**Comment by evetsso** [comment]
Closing this issue then.  Please feel free to reopen it (or open a new one) if you need anything else.
