### ISSUE TITLE
unkown cmake command "rocm_install"

### ISSUE THREAD

**Issue by xiuyangleiasp** [ROCmSoftwarePlatform/rocFFT#364]
when I build Clients with "cmake -DCMAKE_CXX_COMPILER=hipcc -DCMAKE_PREFIX_PAHT=/pathTo/rocfft-lib .."
I always got error:
" Unkown Cmake command "rocm_install "
and my rocm=4.1.0
How can I fix it? 
Thanks

**Comment by cgmb** [comment]
`rocm_install` is defined in `ROCMInstallTargets.cmake` from rocm-cmake. The rocFFT clients sub-project doesn't appear to be able to build independently, as it is depending on [the root CMakeLists.txt](https://github.com/ROCmSoftwarePlatform/rocFFT/blob/50e5b6255943cb6ab5ee4a72485603effacf22c1/CMakeLists.txt#L93) to include that module.

I suspect you could add
```
find_package( ROCM 0.7.3 REQUIRED CONFIG PATHS ${ROCM_PATH} /opt/rocm)
include(ROCMInstallTargets)
```
shortly after the call to `project` in `clients/CMakeLists.txt` for a temporary workaround, though an actual rocFFT developer might have better advice.

**Comment by xiuyangleiasp** [comment]
OK, I will try it. thanks

**Comment by evetsso** [comment]
Some changes have gone into the master branch recently to allow individual client directories (e.g. `clients/tests`, `clients/rider`, `clients/samples/rocfft`) to be their own top-level CMake directories.  The `clients` dir is not currently intended to be its own top-level directory, though @cgmb's workaround should work.
