### ISSUE TITLE
rocFFT inplace implementation

### ISSUE THREAD

**Issue by vasslavich** [ROCmSoftwarePlatform/rocFFT#366]
Hello!
From the previous [post](https://github.com/ROCmSoftwarePlatform/rocFFT/issues/354), I found out that _rocFFT_ uses _Stockham_ radix-2 algorithm. But, unlike _Cooley-Tukey_, it is not an algorithm that allows to compute FFT with **inplace** mode explicitly. I wanted to try experimenting with the butterfly size and radix-4/8. But, I can't figure out how _rocFFT_ uses _Stockham_ with **inplace** mode :  does rocFFT use an additional GPU memory with a size equal to the input for temporary values of a butterfly's output? 

Thanks!

**Comment by feizheng10** [comment]
Yep, technically, Stockham needs outplace. 
When the problem size fits into lds, we could take the lds space to do Stockham FFT, in which no extra global memory and registers required.

**Comment by malcolmroberts** [comment]
rocFFT will allocate work buffers in vram if the algorithm can't be done in-place.  Out-of-place transforms may also use extra work memory.  You can get the work buffer size with `rocfft_plan_get_work_buffer_size`.  This doesn't count twiddle tables, which are typically a few kB.
