### ISSUE TITLE
rocFFT-rocn-5.1.3 unit test fails 116 suites on Radeon VII in an unexpected way

### ISSUE THREAD

**Issue by littlewu2508** [ROCmSoftwarePlatform/rocFFT#369]
### What is the expected behavior
-  The unit test `rocfft-selftest` passed on Radeon VII

### What actually happens
-  There are 116 failed tests, must of which have the wrong order of magnitude. Tests passed on Radeon 6700xt, which is quite surprising to me.

### Environment
| Hardware | description |
|-----|-----|
| GPU | AMD Radeon VII |
| CPU | AMD Ryzen 7 5800X 8-Core Processor |

| Software | version |
|-----|-----|
| ROCK | Linux kernel 5.18.10 |
| ROCR | rocm-5.1.3 |
| HIPCC | rocm-5.1.3 |
| Library | rocm-5.1.3 |

**Comment by littlewu2508** [comment]
An example of failed test:

```
[ RUN      ] ListParamTest/BasicInterfaceDouble3DBasisTest.Inv/54
/fast/portage/sci-libs/rocFFT-5.1.3/work/rocFFT-rocm-5.1.3/clients/selftest/test_complex.cpp:105: Failure
Expected: (fabs(maxRefReal - maxTstReal)) <= (fabs(maxRefReal * 0.000001)), actual: 1.8e+06 vs 2.88
/fast/portage/sci-libs/rocFFT-5.1.3/work/rocFFT-rocm-5.1.3/clients/selftest/test_complex.cpp:106: Failure
Expected: (fabs(maxRefImag - maxTstImag)) <= (fabs(maxRefImag * 0.000001)), actual: 1.44e+06 vs 3.24
/fast/portage/sci-libs/rocFFT-5.1.3/work/rocFFT-rocm-5.1.3/clients/selftest/test_complex.cpp:109: Failure
Expected: (fabs(N * ref[maxRefRealIdx][0] - tst[maxRefRealIdx][0])) <= (fabs(maxRefReal * 0.000001)), actual: 2.87997e+06 vs 2.88
/fast/portage/sci-libs/rocFFT-5.1.3/work/rocFFT-rocm-5.1.3/clients/selftest/test_complex.cpp:111: Failure
Expected: (fabs(N * ref[maxTstRealIdx][0] - tst[maxTstRealIdx][0])) <= (fabs(maxRefReal * 0.000001)), actual: 1.07999e+06 vs 2.88
/fast/portage/sci-libs/rocFFT-5.1.3/work/rocFFT-rocm-5.1.3/clients/selftest/test_complex.cpp:114: Failure
Expected: (fabs(N * ref[maxRefImagIdx][1] - tst[maxRefImagIdx][1])) <= (fabs(maxRefImag * 0.000001)), actual: 3.24002e+06 vs 3.24
/fast/portage/sci-libs/rocFFT-5.1.3/work/rocFFT-rocm-5.1.3/clients/selftest/test_complex.cpp:116: Failure
Expected: (fabs(N * ref[maxTstImagIdx][1] - tst[maxTstImagIdx][1])) <= (fabs(maxRefImag * 0.000001)), actual: 1.79998e+06 vs 3.24
```

**Comment by littlewu2508** [comment]
The complete test log:

[test.log.gz](https://github.com/ROCmSoftwarePlatform/rocFFT/files/9102538/test.log.gz)

**Comment by feizheng10** [comment]
We could reproduce the problem with rocm 5.1.3.
However, it seems there is no problem rocFFT releases for rocm 5.1/5.2 on rocm 5.2 stack, which indicates the problem is not coming from rocFFT itself.
Could you have a try on rocm 5.2 please?

**Comment by littlewu2508** [comment]
> However, it seems there is no problem rocFFT releases for rocm 5.1/5.2 on rocm 5.2 stack
Do you mean compiling rocFFT using rocm-5.2 stack? I'll have a try

However since the problem is reproducible, and the bias is large, I suggest to report it to the release team. This means the entire 5.1.3 stack has this hidden problem (end users usually stay at a coherent version) and may cause undetected numeric error in actual deployment.
