### ISSUE TITLE
Is there support for fp16 Complex-to-Complex transforms?

### ISSUE THREAD

**Issue by vasslavich** [ROCmSoftwarePlatform/rocFFT#370]
Hello!
I'm searching a way to implement **fp16** _complex-to-complex_ 1D transforms, is there the functionality in the library or any workaround?
Thank!

**Comment by evetsso** [comment]
Currently, fp16 is not supported by the library.  It's something we may add in the future, but at this time there is no support.

**Comment by vasslavich** [comment]
Thank you very much! Now I will know.

**Comment by evetsso** [comment]
Circling back to this old issue - FP16 support has now been implemented in the develop branch.  It has not been extensively tuned yet, but should be functional.
