### ISSUE TITLE
The case with 768 can pass the accuracy test in the rocm-4.1.0 but fails in the rocm-4.5.2, Do you know why？

### ISSUE THREAD

**Issue by chenyu1994** [ROCmSoftwarePlatform/rocFFT#373]
### What is the expected behavior
-  

### What actually happens
-  

### How to reproduce
-  

### Environment
| Hardware | description |
|-----|-----|
| GPU | device string |
| CPU | device string |

| Software | version |
|-----|-----|
| ROCK | v0.0 |
| ROCR | v0.0 |
| HCC | v0.0 |
| Library | v0.0 |

**Comment by evetsso** [comment]
In case anyone's wondering, this was caused by a compiler bug that was introduced in 4.5.x and fixed in 5.0.
