### ISSUE TITLE
Test failed on Radeon VII: Assertion `childNodes.size() >= 3 && childNodes.size() < 6' failed

### ISSUE THREAD

**Issue by littlewu2508** [ROCmSoftwarePlatform/rocFFT#399]
### What is the expected behavior
-  rocfft-test passes

### What actually happens
-  Test suite `sbrc_3D/accuracy_test.vs_fftw/complex_forward_len_10_128_200_double_ip_batch_2_istride_1_CI_ostride_1_CI_idist_0_odist_0_ioffset_0_0_ooffset_0_0` returns `rocfft-test: /fast/portage/sci-libs/rocFFT-5.4.3/work/rocFFT-rocm-5.4.3/library/src/tree_node_3D.cpp:395: virtual void BLOCKRC3DNode::AssignParams_internal(): Assertion childNodes.size() >= 3 && childNodes.size() < 6' failed.`
- Here `childNodes.size()` returns 6 which triggers this assertion error.

### How to reproduce
-  Run rocfft-test with ROCm-5.4.3 stack, based on upstream clang-15, on Radeon VII

### Environment
| Hardware | description |
|-----|-----|
| GPU | AMD Radeon VII |
| CPU | AMD Ryzen 7 5800X |

| Software | version |
|-----|-----|
| ROCK | Upstream Linux v6.2.2 |
| ROCR |rocm- 5.4.3 |
| HIP | rocm-5.4.3, clang-15.0.7 |
| Library | rocm-5.4.3 |

**Comment by littlewu2508** [comment]
If I comment-out this assertion, the test passes.

**Comment by evetsso** [comment]
This has been fixed with ffde44d2b6a0a30bc70a340080ce944f5c554caa.  Thanks for the bug report!
