### ISSUE TITLE
Multi-gpu multi-node FFT

### ISSUE THREAD

**Issue by pelahi** [ROCmSoftwarePlatform/rocFFT#437]
I am just wondering if there are plans to have multi-gpu version of this library analogues to the cuFFTMp library. This would be very useful.

**Comment by doctorcolinsmith** [comment]
Hello @pelahi.  We will consider multi-GPU support in the future; however, it is not yet committed to a particular release.  Thanks for the input.

**Comment by malcolmroberts** [comment]
@pelahi - multi-GPU is definitely something that we would like to consider.  Could you tell use something about your use case?  Knowing more about user needs really helps us prioritize development.

**Comment by pelahi** [comment]
Hi @malcolmroberts , so there are several use cases but I said it boils down to doing FFT's of large grids. 

The upcoming SKA radio telescopes (one of the biggest multi-nation science project) will be trying to process very larger grids (double precision complex numbers, ~1e5^2, roughly 149 GB just to store input data). Such a grid is too large to fit on current MI250x and even later generation GPUs. A simple, natural way of addressing this issue would be multi-GPU FFTs. 

I am not directly working for the SKA but I am at the Pawsey Supercomputing Research Centre and am heavily involved in the development of radio astronomy software. We have an AMD system and ideally would like to trial some precursor software and see if we can process SKA scale input data. 

Having the possibility of running the science processing on more than a single GPU vendor because there are libraries that can run on multiple GPU architectures can only be a good thing.
