### ISSUE TITLE
Failure in random_real_3d/random_params.vs_fftw on ROCm 5.5

### ISSUE THREAD

**Issue by cgmb** [ROCmSoftwarePlatform/rocFFT#445]
### What is the expected behavior
-  All rocfft tests pass.

### What actually happens
```
[ RUN      ] random_real_3d/random_params.vs_fftw/0
unknown file: Failure
C++ exception with description "rocFFT plan execution failure"
he test body.

[  FAILED  ] random_real_3d/random_params.vs_fftw/0, where
= (0, 3, 1, 1, 2) (877 ms)
[ RUN      ] random_real_3d/random_params.vs_fftw/1
unknown file: Failure
C++ exception with description "rocFFT plan execution failure"
he test body.

[  FAILED  ] random_real_3d/random_params.vs_fftw/1, where
GetParam() = (0, 3, 1, 1, 3) (960 ms)
```

With `ROCFFT_LAYER=1` enabled: [rocfft-verbose-log.txt](https://github.com/ROCmSoftwarePlatform/rocFFT/files/13552383/rocfft-verbose-log.txt)

### How to reproduce
```
docker run -it --device=/dev/dri --device=/dev/kfd --security-opt seccomp=unconfined --group-add=video --group-add=$(getent group render | cut -d: -f3) debian:sid
apt install librocfft0-tests
/usr/libexec/rocm/librocfft0-tests/rocfft-test 
--gtest_filter='random_real_3d/random_params.vs_fftw/0:random_real_3d/random_params.vs_fftw/1' 
--seed 190206186
```

### Environment
| Hardware | description |
|-----|-----|
| GPU | Radeon VII |

| Software | version |
|-----|-----|
| ROCK | v0.0 |
| ROCR | 5.2.3 |
| Library | v1.0.21 |

### Other Trackers
Debian Bug: https://bugs.debian.org/1057251

**Comment by evetsso** [comment]
I've reproduced this with ROCm 5.5 and confirmed it's fixed by 7fa4850d6c7efb875dcb236b5759278aa1138070 in ROCm 5.6.
