### ISSUE TITLE
Out-of-bounds read in rocfft-test on Rembrandt APU with Linux 6.10

### ISSUE THREAD

**Issue by cgmb** [ROCmSoftwarePlatform/rocFFT#519]
### What is the expected behavior
- rocfft-test should skip tests on APU systems when there is insufficient memory available.

### What actually happens
- Linux 6.10 can dynamically allocate more memory for the GPU on APU systems and rocfft-test now crashes with an out-of-bounds read.

### How to reproduce
- Start with `debian:unstable` docker image
- Run `apt install librocfft0-tests`
- Run `/usr/libexec/rocm/librocfft0-tests/rocfft-test`

### Other Information
Debian Bug Report: https://bugs.debian.org/1082888

The rocfft tests are crashing on gfx1035 after updating the kernel from
bookworm to bookworm-backports (6.1 to 6.10). This can be seen be comparing
these two nearly identical runs from before (1) and after (2) installing a new
kernel.

1: https://ci.rocm.debian.net/data/autopkgtest/unstable/amd64+gfx1035/r/rocfft/33925/log.gz ([artifacts](https://ci.rocm.debian.net/data/autopkgtest/unstable/amd64+gfx1035/r/rocfft/33925/artifacts.tar.gz))
2: https://ci.rocm.debian.net/data/autopkgtest/unstable/amd64+gfx1035/r/rocfft/34278/log.gz ([artifacts](https://ci.rocm.debian.net/data/autopkgtest/unstable/amd64+gfx1035/r/rocfft/34278/artifacts.tar.gz))

This is the failing test:
```
498s [ RUN      ] pow2_1D/accuracy_test.vs_fftw/complex_forward_len_268435456_single_ip_batch_4_istride_1_CI_ostride_1_CI_idist_268435456_odist_268435456_ioffset_0_0_ooffset_0_0
558s Killed
558s dmesg: read kernel buffer failed: Operation not permitted
```

It seems that previously it was skipped:
```
162s [ RUN      ] pow2_1D/accuracy_test.vs_fftw/complex_forward_len_268435456_single_ip_batch_4_istride_1_CI_ostride_1_CI_idist_268435456_odist_268435456_ioffset_0_0_ooffset_0_0
162s clients/tests/accuracy_test.h:1260: Skipped
162s Raw problem size (9 GiB) raw data too large for device
```

There are other tests that use much more RAM that are still skipped, even with the newer kernel:
```
395s [ RUN      ] pow2_1D/accuracy_test.vs_fftw/complex_forward_len_268435456_double_op_batch_4_istride_1_CI_ostride_1_CI_idist_268435456_odist_268435456_ioffset_0_0_ooffset_0_0
395s clients/tests/accuracy_test.h:1214: Skipped
395s needed_ramgb: 96, ramgb limit: 61.
```

The failure therefore appears to be due to changes in the GPU memory capacity
reported for the APUs. In Linux 6.10, the driver is able to dynamically
allocate more system memory for use by the GPU.

The rocfft library queries the amount of memory available on the device and it
skips tests that would use more memory than is available. I suspect that the
allocation for this test is failing but the library attempts to use the
returned value anyway.

While there may be 61GB of memory available in theory, it might be that there
are other factors that reduce that amount. For example, allocations in host
memory might reduce the available memory for the device in APU systems like
this. While the device memory limit might be 61GB, you cannot allocate 40GB of
host memory and 40GB of device memory, as they come from the same pool.

The rocfft-test client provides the --R <gb> and --V <gb> options to explicitly
specify the host and device memory limits, respectively. That may be a good
workaround for the moment, although it would be better if rocfft-test could
query the system hardware and choose appropriate defaults.

### Environment
| Hardware | description |
|-----|-----|
| GPU | AMD Ryzen 7 7735HS with Radeon Graphics (gfx1035) |
| CPU | AMD Ryzen 7 7735HS with Radeon Graphics |

#### Software
Debian Unstable running on the Debian bookworm-backports kernel

##### Packages
libamd-comgr2	6.0+git20231212.4510c28+dfsg-3+b1
libamdhip64-5	5.7.1-5
libapparmor1	3.1.7-1+b1
libboost-program-options1.83.0	1.83.0-3.2
libdrm-amdgpu1	2.4.123-1
libdrm-common	2.4.123-1
libdrm2	2.4.123-1
libedit2	3.1-20240808-1
libelf1t64	0.191-2
libfftw3-double3	3.3.10-1+b3
libfftw3-single3	3.3.10-1+b3
libgomp1	14.2.0-5
libhiprand1	5.7.1-4
libhsa-runtime64-1	5.7.1-3
libhsakmt1	6.1.2+ds-1
libicu72	72.1-5
libllvm17t64	1:17.0.6-18
libnuma1	2.0.18-1
librocfft0	6.1.2-1
librocfft0-tests	6.1.2-1
librocrand1	5.7.1-4
libsqlite3-0	3.46.1-1
libxml2	2.12.7+dfsg+really2.9.14-0.1
libz3-4	4.8.12-3.1+b2
sudo	1.9.15p5-3+b1

##### Kernel
Linux nightwatch 6.10.6+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.10.6-1~bpo12+1 (2024-08-26) x86_64 GNU/Linux

**Comment by evetsso** [comment]
cb968ed9ed83babb90baa2990a17766db119af42 addresses this by ensuring that "device" memory is not also counted as "host" memory when we work out what problem sizes will fit.

**Comment by cgmb** [comment]
Thanks Steve!
