### ISSUE TITLE
[Issue]: Empty AMDGPU_TARGETS_AOT list leads to build failure

### ISSUE THREAD

**Issue by seragh** [ROCmSoftwarePlatform/rocFFT#529]
### Problem Description

When specifying a subset of gfx* for AMDGPU_TARGETS then filtering as done in https://github.com/ROCm/rocFFT/blob/d2d619a9b6fe0ecb2123d10f36caf3b2b23dddc5/library/src/CMakeLists.txt#L514-L522 may lead to an empty list. Which in turn will result in a build failure.

NB, Maybe leave it to user to skip aot or not. At least that is my expectation for the option ROCFFT_KERNEL_CACHE_ENABLE and the filtering should probably be a separate option enabled for official builds.

### Operating System

-

### CPU

-

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.1.0

**Comment by evetsso** [comment]
Hi @seragh this has already been addressed by c75320a41830173ac4ac0de39c4650b170b47f3f, which makes the build tolerate an empty list as a side effect.  It's the change to rocfft_aot_helper.cpp that does this.

Therefore, I'm closing this issue.  Please reach out if you find this commit doesn't help the problem.
