### ISSUE TITLE
Failed in Linking librocfft.so

### ISSUE THREAD

**Issue by aaronenyeshi** [ROCmSoftwarePlatform/rocFFT#94]
### What is the expected behavior
-  Build correctly.

### What actually happens
-  I am getting this error message:
```
[100%] Linking CXX shared library librocfft.so
ar: /root/rocFFT/build/release/library/src/device/librocfft-device.so.0.3.0.0-54be23a: File format not recognized
ls: cannot access '/tmp/tmp.ccMFwNMSbU/librocfft-device.so.0.3.0.0-54be23a/*.o': No such file or directory
```

### How to reproduce
-  Install latest HCC and HIP, then run build rocFFT using these steps
-  git clone rocFFT and checkout latest develop branch
-  cd rocFFT; mkdir build; cd build; mkdir release; cd release
-  CXX=/opt/rocm/bin/hcc cmake ../..
-  make -j16 <-- errors here at linking librocfft.so

### Environment
| Hardware | description |
|-----|-----|
| GPU | Fiji [Radeon R9 FURY / NANO Series] |
| CPU | Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz |

| Software | version |
|-----|-----|
| ROCK | v0.0 |
| ROCR | v0.0 |
| HCC | clang_tot_upgrade branch |
| Library | v0.0 |
| HIP | master branch |

**Comment by aaronenyeshi** [comment]
I just tested on older rocFFT, it doesn't break on commit b3ac0cc4117dab54ad7c4612c9c31033d61476c8

**Comment by kknox** [comment]
I think this is a change that happened upstream in rocm-cmake.  By default, I think rocm-cmake tries to tag packages with a git hash.  I believe there is a way to turn it off, I'll take a look at it.

**Comment by aaronenyeshi** [comment]
Thanks @kknox !
